/**
 * Slugs / sous-domaines interdits pour les boutiques.
 * Doit rester aligné avec public.is_slug_reserved / is_subdomain_reserved (SQL).
 */

const RESERVED_STORE_SLUGS_LIST = [
  // Infra & plateforme
  'www',
  'web',
  'admin',
  'api',
  'app',
  'apps',
  'support',
  'help',
  'helps',
  'my',
  'mail',
  'email',
  'ftp',
  'smtp',
  'pop',
  'pop3',
  'imap',
  'blog',
  'shop',
  'store',
  'stores',
  'marketplace',
  'dashboard',
  'account',
  'accounts',
  'auth',
  'login',
  'logout',
  'signup',
  'register',
  'password',
  'reset',
  'verify',
  'confirm',
  'settings',
  'profile',
  'billing',
  'payment',
  'payments',
  'checkout',
  'cart',
  'order',
  'orders',
  'product',
  'products',
  'category',
  'categories',
  'search',
  'filter',
  'filters',
  'about',
  'contact',
  'terms',
  'privacy',
  'legal',
  'faq',
  'docs',
  'documentation',
  'status',
  'health',
  'ping',
  'test',
  'testing',
  'staging',
  'dev',
  'development',
  'cdn',
  'assets',
  'static',
  'media',
  'images',
  'files',
  'api-docs',
  'swagger',
  'graphql',
  'webhook',
  'webhooks',
  'admin-panel',
  'cpanel',
  'phpmyadmin',
  'wp-admin',
  'mx',
  'ns1',
  'ns2',
  'dns',
  'domain',
  'domains',
  'subdomain',
  'wildcard',
  'catch-all',
  'default',
  'fallback',
  'root',
  'null',
  'undefined',
  'system',
  'sys',
  'internal',
  'private',
  'public',
  'secure',
  'security',
  'ssl',
  'oauth',
  'sso',
  'backend',
  'frontend',
  'server',
  'servers',
  'client',
  'clients',
  'portal',
  'console',
  'ops',
  'monitoring',
  'metrics',
  'logs',
  'log',
  'beta',
  'demo',
  'preview',
  'localhost',
  'local',
  'prod',
  'production',
  'staging-api',
  'cdn-assets',
  // Marque Emarzona / produit
  'emarzona',
  'emarzona-admin',
  'emarzona-api',
  'emarzona-app',
  'myemarzona',
  'geniuspay',
  'genius-pay',
  'protect',
  'emarzona-protect',
  // Messagerie / réseaux (usurpation)
  'whatsapp',
  'whats-app',
  'facebook',
  'fb',
  'instagram',
  'insta',
  'twitter',
  'x',
  'tiktok',
  'youtube',
  'telegram',
  'snapchat',
  'discord',
  'linkedin',
  'pinterest',
  'messenger',
  'gmail',
  'outlook',
  'hotmail',
  'yahoo',
  // Big tech / finance (usurpation)
  'google',
  'apple',
  'amazon',
  'microsoft',
  'meta',
  'paypal',
  'stripe',
  'visa',
  'mastercard',
  'orange-money',
  'orangemoney',
  'moov',
  'moov-money',
  'wave',
  'mtn',
  'mtn-momo',
  'momo',
  // Autorités / institutions (sensibles)
  'police',
  'gendarmerie',
  'gouvernement',
  'government',
  'etat',
  'state',
  'justice',
  'tribunal',
  'armee',
  'army',
  'militaire',
  'military',
  'douane',
  'customs',
  'ministere',
  'ministry',
  'mairie',
  'prefecture',
  'prefectoral',
  'ambassade',
  'embassy',
  'onu',
  'un',
  'oms',
  'who',
  'impots',
  'taxes',
  'fiscal',
  'securite',
  'urgence',
  'emergency',
  'sos',
  // Abus / fraude
  'scam',
  'phishing',
  'fraud',
  'fraude',
  'hack',
  'hacker',
  'virus',
  'malware',
  'spam',
] as const;

/** Liste exportée (compat `RESERVED_SUBDOMAINS.includes`). */
export const RESERVED_STORE_SLUGS: readonly string[] = RESERVED_STORE_SLUGS_LIST;

const RESERVED_STORE_SLUG_SET = new Set(RESERVED_STORE_SLUGS_LIST.map(slug => slug.toLowerCase()));

export function normalizeStoreSlugCandidate(value: string): string {
  return value.toLowerCase().trim();
}

/** true si le slug est réservé / sensible / protégé. */
export function isReservedStoreSlug(slug: string): boolean {
  const normalized = normalizeStoreSlugCandidate(slug);
  if (!normalized) return false;
  return RESERVED_STORE_SLUG_SET.has(normalized);
}
