/** Layout types for context sidebars and route detection. */
export type LayoutType =
  | 'default'
  | 'settings'
  | 'emails'
  | 'products'
  | 'orders'
  | 'customers'
  | 'analytics'
  | 'account'
  | 'sales'
  | 'finance'
  | 'marketing'
  | 'systems'
  | 'store'
  | 'bookings'
  | 'inventory'
  | 'shipping'
  | 'promotions'
  | 'courses'
  | 'affiliate'
  | 'digital-portal'
  | 'physical-portal'
  | 'minimal';
