import {
  CheckCircle2, CreditCard, XCircle,
} from 'lucide-react';
import type { PageConfig } from './types';

export const checkoutPagesConfig: PageConfig[] = [
  {
    id: 'checkout',
    name: 'Checkout',
    route: '/checkout',
    description: 'Personnalisez tous les éléments de la page de paiement',
    icon: CreditCard,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'checkout.header.title',
            defaultValue: 'Finaliser la commande',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'checkout.header.subtitle',
            defaultValue: 'Remplissez vos informations pour compléter votre achat',
          },
        ],
      },
      {
        id: 'shipping',
        name: 'Informations de livraison',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre section',
            type: 'text',
            key: 'checkout.shipping.title',
            defaultValue: 'Informations de livraison',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre section',
            type: 'textarea',
            key: 'checkout.shipping.subtitle',
            defaultValue: 'Où souhaitez-vous recevoir votre commande ?',
          },
          {
            id: 'fullNameLabel',
            label: 'Label Nom complet',
            type: 'text',
            key: 'checkout.shipping.fullNameLabel',
            defaultValue: 'Nom complet',
          },
          {
            id: 'emailLabel',
            label: 'Label Email',
            type: 'text',
            key: 'checkout.shipping.emailLabel',
            defaultValue: 'Email',
          },
          {
            id: 'phoneLabel',
            label: 'Label Téléphone',
            type: 'text',
            key: 'checkout.shipping.phoneLabel',
            defaultValue: 'Téléphone',
          },
          {
            id: 'addressLabel',
            label: 'Label Adresse',
            type: 'text',
            key: 'checkout.shipping.addressLabel',
            defaultValue: 'Adresse',
          },
          {
            id: 'cityLabel',
            label: 'Label Ville',
            type: 'text',
            key: 'checkout.shipping.cityLabel',
            defaultValue: 'Ville',
          },
          {
            id: 'countryLabel',
            label: 'Label Pays',
            type: 'text',
            key: 'checkout.shipping.countryLabel',
            defaultValue: 'Pays',
          },
          {
            id: 'postalCodeLabel',
            label: 'Label Code postal',
            type: 'text',
            key: 'checkout.shipping.postalCodeLabel',
            defaultValue: 'Code postal',
          },
        ],
      },
      {
        id: 'summary',
        name: 'Récapitulatif',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre récapitulatif',
            type: 'text',
            key: 'checkout.summary.title',
            defaultValue: 'Récapitulatif',
          },
          {
            id: 'subtotalLabel',
            label: 'Label Sous-total',
            type: 'text',
            key: 'checkout.summary.subtotalLabel',
            defaultValue: 'Sous-total',
          },
          {
            id: 'shippingLabel',
            label: 'Label Livraison',
            type: 'text',
            key: 'checkout.summary.shippingLabel',
            defaultValue: 'Livraison',
          },
          {
            id: 'taxLabel',
            label: 'Label Taxes',
            type: 'text',
            key: 'checkout.summary.taxLabel',
            defaultValue: 'Taxes',
          },
          {
            id: 'discountLabel',
            label: 'Label Remise',
            type: 'text',
            key: 'checkout.summary.discountLabel',
            defaultValue: 'Remise',
          },
          {
            id: 'totalLabel',
            label: 'Label Total',
            type: 'text',
            key: 'checkout.summary.totalLabel',
            defaultValue: 'Total',
          },
          {
            id: 'couponPlaceholder',
            label: 'Placeholder Code promo',
            type: 'text',
            key: 'checkout.summary.couponPlaceholder',
            defaultValue: 'Code promo',
          },
          {
            id: 'giftCardPlaceholder',
            label: 'Placeholder Carte cadeau',
            type: 'text',
            key: 'checkout.summary.giftCardPlaceholder',
            defaultValue: 'Code carte cadeau',
          },
          {
            id: 'proceedButton',
            label: 'Bouton Procéder au paiement',
            type: 'text',
            key: 'checkout.summary.proceedButton',
            defaultValue: 'Procéder au paiement',
          },
        ],
      },
      {
        id: 'payment',
        name: 'Paiement',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre section paiement',
            type: 'text',
            key: 'checkout.payment.title',
            defaultValue: 'Méthode de paiement',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre section paiement',
            type: 'textarea',
            key: 'checkout.payment.subtitle',
            defaultValue: 'Choisissez votre méthode de paiement',
          },
          {
            id: 'secureMessage',
            label: 'Message Sécurisé',
            type: 'textarea',
            key: 'checkout.payment.secureMessage',
            defaultValue: 'Vos informations de paiement sont sécurisées et cryptées',
          },
        ],
      },
      {
        id: 'errors',
        name: "Messages d'erreur",
        type: 'content',
        elements: [
          {
            id: 'emptyCart',
            label: 'Message Panier vide',
            type: 'textarea',
            key: 'checkout.errors.emptyCart',
            defaultValue: 'Votre panier est vide',
          },
          {
            id: 'validationError',
            label: 'Message Erreur validation',
            type: 'textarea',
            key: 'checkout.errors.validationError',
            defaultValue: 'Veuillez remplir tous les champs obligatoires',
          },
          {
            id: 'paymentError',
            label: 'Message Erreur paiement',
            type: 'textarea',
            key: 'checkout.errors.paymentError',
            defaultValue: 'Une erreur est survenue lors du paiement',
          },
        ],
      },
    ],
  },
  {
    id: 'paymentSuccess',
    name: 'Paiement Réussi',
    route: '/payment/success',
    description: 'Personnalisez tous les éléments de la page de confirmation de paiement',
    icon: CheckCircle2,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'paymentSuccess.header.title',
            defaultValue: 'Paiement réussi ! 🎉',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'paymentSuccess.header.subtitle',
            defaultValue: 'Merci pour votre achat ! Votre paiement a été confirmé.',
          },
          {
            id: 'processingMessage',
            label: 'Message En traitement',
            type: 'textarea',
            key: 'paymentSuccess.header.processingMessage',
            defaultValue: 'Votre paiement est en cours de traitement. Veuillez patienter...',
          },
          {
            id: 'completedMessage',
            label: 'Message Complété',
            type: 'textarea',
            key: 'paymentSuccess.header.completedMessage',
            defaultValue: 'Merci pour votre achat ! Votre paiement a été confirmé avec succès.',
          },
        ],
      },
      {
        id: 'actions',
        name: 'Actions',
        type: 'content',
        elements: [
          {
            id: 'downloadsButton',
            label: 'Bouton Mes Téléchargements',
            type: 'text',
            key: 'paymentSuccess.actions.downloadsButton',
            defaultValue: 'Mes Téléchargements',
          },
          {
            id: 'ordersButton',
            label: 'Bouton Mes Commandes',
            type: 'text',
            key: 'paymentSuccess.actions.ordersButton',
            defaultValue: 'Mes Commandes',
          },
          {
            id: 'continueShoppingButton',
            label: 'Bouton Continuer les achats',
            type: 'text',
            key: 'paymentSuccess.actions.continueShoppingButton',
            defaultValue: 'Continuer les achats',
          },
        ],
      },
      {
        id: 'license',
        name: 'Information Licence',
        type: 'content',
        elements: [
          {
            id: 'plrTitle',
            label: 'Titre Licence PLR',
            type: 'text',
            key: 'paymentSuccess.license.plrTitle',
            defaultValue: 'Licence PLR (droits de label privé)',
          },
          {
            id: 'copyrightedTitle',
            label: 'Titre Protégé',
            type: 'text',
            key: 'paymentSuccess.license.copyrightedTitle',
            defaultValue: "Protégé par droit d'auteur",
          },
          {
            id: 'standardTitle',
            label: 'Titre Licence standard',
            type: 'text',
            key: 'paymentSuccess.license.standardTitle',
            defaultValue: 'Licence standard',
          },
          {
            id: 'termsMessage',
            label: 'Message Conditions',
            type: 'textarea',
            key: 'paymentSuccess.license.termsMessage',
            defaultValue: "Veuillez respecter les conditions d'utilisation de ce contenu.",
          },
        ],
      },
    ],
  },
  {
    id: 'paymentCancel',
    name: 'Paiement Annulé',
    route: '/payment/cancel',
    description: "Personnalisez tous les éléments de la page d'annulation de paiement",
    icon: XCircle,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'paymentCancel.header.title',
            defaultValue: 'Paiement annulé ❌',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'paymentCancel.header.subtitle',
            defaultValue: "Votre paiement n'a pas été finalisé. Aucun montant n'a été débité.",
          },
        ],
      },
      {
        id: 'actions',
        name: 'Actions',
        type: 'content',
        elements: [
          {
            id: 'backToMarketplaceButton',
            label: 'Bouton Retour marketplace',
            type: 'text',
            key: 'paymentCancel.actions.backToMarketplaceButton',
            defaultValue: 'Retour au marketplace',
          },
          {
            id: 'retryButton',
            label: 'Bouton Réessayer',
            type: 'text',
            key: 'paymentCancel.actions.retryButton',
            defaultValue: 'Réessayer le paiement',
          },
        ],
      },
      {
        id: 'license',
        name: 'Information Licence',
        type: 'content',
        elements: [
          {
            id: 'plrTitle',
            label: 'Titre Licence PLR',
            type: 'text',
            key: 'paymentCancel.license.plrTitle',
            defaultValue: 'Licence PLR (droits de label privé)',
          },
          {
            id: 'copyrightedTitle',
            label: 'Titre Protégé',
            type: 'text',
            key: 'paymentCancel.license.copyrightedTitle',
            defaultValue: "Protégé par droit d'auteur",
          },
          {
            id: 'standardTitle',
            label: 'Titre Licence standard',
            type: 'text',
            key: 'paymentCancel.license.standardTitle',
            defaultValue: 'Licence standard',
          },
          {
            id: 'termsMessage',
            label: 'Message Conditions',
            type: 'textarea',
            key: 'paymentCancel.license.termsMessage',
            defaultValue:
              "Si vous réessayez l'achat, veuillez respecter les conditions d'utilisation.",
          },
        ],
      },
    ],
  },
];
