import {
  Award, Bell, BookOpen, Download, FileText, Gift, Heart, Package, RotateCcw, ShoppingBag, User,
} from 'lucide-react';
import type { PageConfig } from './types';

export const customerPagesConfig: PageConfig[] = [
  {
    id: 'customerPortal',
    name: 'Portail Client',
    route: '/account',
    description: 'Personnalisez tous les éléments du portail client',
    icon: User,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'customerPortal.header.title',
            defaultValue: 'Mon Espace Client',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'customerPortal.header.subtitle',
            defaultValue: 'Gérez vos achats, téléchargements et informations personnelles',
          },
        ],
      },
      {
        id: 'stats',
        name: 'Statistiques',
        type: 'content',
        elements: [
          {
            id: 'totalOrdersLabel',
            label: 'Label Total commandes',
            type: 'text',
            key: 'customerPortal.stats.totalOrders',
            defaultValue: 'Commandes',
          },
          {
            id: 'totalSpentLabel',
            label: 'Label Total dépensé',
            type: 'text',
            key: 'customerPortal.stats.totalSpent',
            defaultValue: 'Total dépensé',
          },
          {
            id: 'digitalProductsLabel',
            label: 'Label Produits digitaux',
            type: 'text',
            key: 'customerPortal.stats.digitalProducts',
            defaultValue: 'Produits digitaux',
          },
          {
            id: 'physicalProductsLabel',
            label: 'Label Produits physiques',
            type: 'text',
            key: 'customerPortal.stats.physicalProducts',
            defaultValue: 'Produits physiques',
          },
          {
            id: 'servicesLabel',
            label: 'Label Services',
            type: 'text',
            key: 'customerPortal.stats.services',
            defaultValue: 'Services',
          },
          {
            id: 'coursesLabel',
            label: 'Label Cours',
            type: 'text',
            key: 'customerPortal.stats.courses',
            defaultValue: 'Cours',
          },
        ],
      },
      {
        id: 'tabs',
        name: 'Onglets',
        type: 'content',
        elements: [
          {
            id: 'overviewTab',
            label: "Onglet Vue d'ensemble",
            type: 'text',
            key: 'customerPortal.tabs.overview',
            defaultValue: "Vue d'ensemble",
          },
          {
            id: 'digitalTab',
            label: 'Onglet Digital',
            type: 'text',
            key: 'customerPortal.tabs.digital',
            defaultValue: 'Digital',
          },
          {
            id: 'physicalTab',
            label: 'Onglet Physique',
            type: 'text',
            key: 'customerPortal.tabs.physical',
            defaultValue: 'Physique',
          },
          {
            id: 'servicesTab',
            label: 'Onglet Services',
            type: 'text',
            key: 'customerPortal.tabs.services',
            defaultValue: 'Services',
          },
          {
            id: 'coursesTab',
            label: 'Onglet Cours',
            type: 'text',
            key: 'customerPortal.tabs.courses',
            defaultValue: 'Cours',
          },
        ],
      },
      {
        id: 'actions',
        name: 'Actions rapides',
        type: 'content',
        elements: [
          {
            id: 'viewOrdersButton',
            label: 'Bouton Voir commandes',
            type: 'text',
            key: 'customerPortal.actions.viewOrders',
            defaultValue: 'Voir mes commandes',
          },
          {
            id: 'viewDownloadsButton',
            label: 'Bouton Voir téléchargements',
            type: 'text',
            key: 'customerPortal.actions.viewDownloads',
            defaultValue: 'Mes téléchargements',
          },
          {
            id: 'viewProfileButton',
            label: 'Bouton Voir profil',
            type: 'text',
            key: 'customerPortal.actions.viewProfile',
            defaultValue: 'Mon profil',
          },
        ],
      },
    ],
  },
  {
    id: 'customerMyOrders',
    name: 'Mes Commandes',
    route: '/account/orders',
    description: 'Personnalisez tous les éléments de la page mes commandes',
    icon: ShoppingBag,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'customerMyOrders.header.title',
            defaultValue: 'Mes Commandes',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'customerMyOrders.header.subtitle',
            defaultValue: 'Consultez toutes vos commandes et leur statut',
          },
        ],
      },
      {
        id: 'stats',
        name: 'Statistiques',
        type: 'content',
        elements: [
          {
            id: 'allLabel',
            label: 'Label Toutes',
            type: 'text',
            key: 'customerMyOrders.stats.all',
            defaultValue: 'Toutes',
          },
          {
            id: 'pendingLabel',
            label: 'Label En attente',
            type: 'text',
            key: 'customerMyOrders.stats.pending',
            defaultValue: 'En attente',
          },
          {
            id: 'processingLabel',
            label: 'Label En traitement',
            type: 'text',
            key: 'customerMyOrders.stats.processing',
            defaultValue: 'En traitement',
          },
          {
            id: 'completedLabel',
            label: 'Label Complétées',
            type: 'text',
            key: 'customerMyOrders.stats.completed',
            defaultValue: 'Complétées',
          },
          {
            id: 'cancelledLabel',
            label: 'Label Annulées',
            type: 'text',
            key: 'customerMyOrders.stats.cancelled',
            defaultValue: 'Annulées',
          },
        ],
      },
      {
        id: 'filters',
        name: 'Filtres',
        type: 'content',
        elements: [
          {
            id: 'searchPlaceholder',
            label: 'Placeholder Recherche',
            type: 'text',
            key: 'customerMyOrders.filters.searchPlaceholder',
            defaultValue: 'Rechercher une commande...',
          },
          {
            id: 'filterAll',
            label: 'Filtre Toutes',
            type: 'text',
            key: 'customerMyOrders.filters.all',
            defaultValue: 'Toutes',
          },
          {
            id: 'filterPending',
            label: 'Filtre En attente',
            type: 'text',
            key: 'customerMyOrders.filters.pending',
            defaultValue: 'En attente',
          },
          {
            id: 'filterProcessing',
            label: 'Filtre En traitement',
            type: 'text',
            key: 'customerMyOrders.filters.processing',
            defaultValue: 'En traitement',
          },
          {
            id: 'filterCompleted',
            label: 'Filtre Complétées',
            type: 'text',
            key: 'customerMyOrders.filters.completed',
            defaultValue: 'Complétées',
          },
          {
            id: 'filterCancelled',
            label: 'Filtre Annulées',
            type: 'text',
            key: 'customerMyOrders.filters.cancelled',
            defaultValue: 'Annulées',
          },
        ],
      },
      {
        id: 'order',
        name: 'Commande',
        type: 'content',
        elements: [
          {
            id: 'orderNumberLabel',
            label: 'Label Numéro commande',
            type: 'text',
            key: 'customerMyOrders.order.orderNumber',
            defaultValue: 'Commande',
          },
          {
            id: 'dateLabel',
            label: 'Label Date',
            type: 'text',
            key: 'customerMyOrders.order.date',
            defaultValue: 'Date',
          },
          {
            id: 'totalLabel',
            label: 'Label Total',
            type: 'text',
            key: 'customerMyOrders.order.total',
            defaultValue: 'Total',
          },
          {
            id: 'statusLabel',
            label: 'Label Statut',
            type: 'text',
            key: 'customerMyOrders.order.status',
            defaultValue: 'Statut',
          },
          {
            id: 'viewButton',
            label: 'Bouton Voir détails',
            type: 'text',
            key: 'customerMyOrders.order.viewButton',
            defaultValue: 'Voir détails',
          },
          {
            id: 'noOrdersMessage',
            label: 'Message Aucune commande',
            type: 'textarea',
            key: 'customerMyOrders.order.noOrders',
            defaultValue: 'Aucune commande pour le moment',
          },
        ],
      },
    ],
  },
  {
    id: 'customerMyDownloads',
    name: 'Mes Téléchargements',
    route: '/account/downloads',
    description: 'Personnalisez tous les éléments de la page mes téléchargements',
    icon: Download,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'customerMyDownloads.header.title',
            defaultValue: 'Mes Téléchargements',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'customerMyDownloads.header.subtitle',
            defaultValue: 'Accédez à tous vos produits digitaux achetés',
          },
          {
            id: 'refreshButton',
            label: 'Bouton Rafraîchir',
            type: 'text',
            key: 'customerMyDownloads.header.refreshButton',
            defaultValue: 'Rafraîchir',
          },
        ],
      },
      {
        id: 'stats',
        name: 'Statistiques',
        type: 'content',
        elements: [
          {
            id: 'totalLabel',
            label: 'Label Total',
            type: 'text',
            key: 'customerMyDownloads.stats.total',
            defaultValue: 'Total',
          },
          {
            id: 'successfulLabel',
            label: 'Label Réussis',
            type: 'text',
            key: 'customerMyDownloads.stats.successful',
            defaultValue: 'Réussis',
          },
          {
            id: 'failedLabel',
            label: 'Label Échoués',
            type: 'text',
            key: 'customerMyDownloads.stats.failed',
            defaultValue: 'Échoués',
          },
          {
            id: 'uniqueProductsLabel',
            label: 'Label Produits uniques',
            type: 'text',
            key: 'customerMyDownloads.stats.uniqueProducts',
            defaultValue: 'Produits uniques',
          },
        ],
      },
      {
        id: 'filters',
        name: 'Filtres',
        type: 'content',
        elements: [
          {
            id: 'searchPlaceholder',
            label: 'Placeholder Recherche',
            type: 'text',
            key: 'customerMyDownloads.filters.searchPlaceholder',
            defaultValue: 'Rechercher un produit...',
          },
          {
            id: 'filterAll',
            label: 'Filtre Tous',
            type: 'text',
            key: 'customerMyDownloads.filters.all',
            defaultValue: 'Tous',
          },
          {
            id: 'filterSuccess',
            label: 'Filtre Réussis',
            type: 'text',
            key: 'customerMyDownloads.filters.success',
            defaultValue: 'Réussis',
          },
          {
            id: 'filterFailed',
            label: 'Filtre Échoués',
            type: 'text',
            key: 'customerMyDownloads.filters.failed',
            defaultValue: 'Échoués',
          },
        ],
      },
      {
        id: 'download',
        name: 'Téléchargement',
        type: 'content',
        elements: [
          {
            id: 'downloadButton',
            label: 'Bouton Télécharger',
            type: 'text',
            key: 'customerMyDownloads.download.downloadButton',
            defaultValue: 'Télécharger',
          },
          {
            id: 'retryButton',
            label: 'Bouton Réessayer',
            type: 'text',
            key: 'customerMyDownloads.download.retryButton',
            defaultValue: 'Réessayer',
          },
          {
            id: 'noDownloadsMessage',
            label: 'Message Aucun téléchargement',
            type: 'textarea',
            key: 'customerMyDownloads.download.noDownloads',
            defaultValue: 'Aucun téléchargement pour le moment',
          },
        ],
      },
    ],
  },
  {
    id: 'customerDigitalPortal',
    name: 'Portail Digital',
    route: '/account/digital',
    description: 'Personnalisez tous les éléments du portail digital',
    icon: Package,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'customerDigitalPortal.header.title',
            defaultValue: 'Mon Portail Digital',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'customerDigitalPortal.header.subtitle',
            defaultValue: 'Gérez tous vos produits digitaux, licences et téléchargements',
          },
        ],
      },
      {
        id: 'tabs',
        name: 'Onglets',
        type: 'content',
        elements: [
          {
            id: 'productsTab',
            label: 'Onglet Produits',
            type: 'text',
            key: 'customerDigitalPortal.tabs.products',
            defaultValue: 'Mes Produits',
          },
          {
            id: 'licensesTab',
            label: 'Onglet Licences',
            type: 'text',
            key: 'customerDigitalPortal.tabs.licenses',
            defaultValue: 'Mes Licences',
          },
          {
            id: 'downloadsTab',
            label: 'Onglet Téléchargements',
            type: 'text',
            key: 'customerDigitalPortal.tabs.downloads',
            defaultValue: 'Téléchargements',
          },
          {
            id: 'statsTab',
            label: 'Onglet Statistiques',
            type: 'text',
            key: 'customerDigitalPortal.tabs.stats',
            defaultValue: 'Statistiques',
          },
          {
            id: 'preferencesTab',
            label: 'Onglet Préférences',
            type: 'text',
            key: 'customerDigitalPortal.tabs.preferences',
            defaultValue: 'Préférences',
          },
        ],
      },
    ],
  },
  {
    id: 'customerPhysicalPortal',
    name: 'Portail Physique',
    route: '/account/physical',
    description: 'Personnalisez tous les éléments du portail produits physiques',
    icon: ShoppingBag,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'customerPhysicalPortal.header.title',
            defaultValue: 'Mon Portail Produits Physiques',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'customerPhysicalPortal.header.subtitle',
            defaultValue: 'Gérez vos commandes, retours, garanties et suivez vos expéditions',
          },
        ],
      },
      {
        id: 'tabs',
        name: 'Onglets',
        type: 'content',
        elements: [
          {
            id: 'ordersTab',
            label: 'Onglet Commandes',
            type: 'text',
            key: 'customerPhysicalPortal.tabs.orders',
            defaultValue: 'Mes Commandes',
          },
          {
            id: 'trackingTab',
            label: 'Onglet Suivi',
            type: 'text',
            key: 'customerPhysicalPortal.tabs.tracking',
            defaultValue: 'Suivi',
          },
          {
            id: 'returnsTab',
            label: 'Onglet Retours',
            type: 'text',
            key: 'customerPhysicalPortal.tabs.returns',
            defaultValue: 'Retours',
          },
          {
            id: 'warrantiesTab',
            label: 'Onglet Garanties',
            type: 'text',
            key: 'customerPhysicalPortal.tabs.warranties',
            defaultValue: 'Garanties',
          },
          {
            id: 'historyTab',
            label: 'Onglet Historique',
            type: 'text',
            key: 'customerPhysicalPortal.tabs.history',
            defaultValue: 'Historique',
          },
        ],
      },
    ],
  },
  {
    id: 'customerMyCourses',
    name: 'Mes Cours',
    route: '/account/courses',
    description: 'Personnalisez tous les éléments de la page mes cours',
    icon: BookOpen,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'customerMyCourses.header.title',
            defaultValue: 'Mes Cours',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'customerMyCourses.header.subtitle',
            defaultValue: 'Suivez votre progression et continuez votre apprentissage',
          },
          {
            id: 'refreshButton',
            label: 'Bouton Rafraîchir',
            type: 'text',
            key: 'customerMyCourses.header.refreshButton',
            defaultValue: 'Rafraîchir',
          },
        ],
      },
      {
        id: 'stats',
        name: 'Statistiques',
        type: 'content',
        elements: [
          {
            id: 'totalLabel',
            label: 'Label Total',
            type: 'text',
            key: 'customerMyCourses.stats.total',
            defaultValue: 'Total',
          },
          {
            id: 'inProgressLabel',
            label: 'Label En cours',
            type: 'text',
            key: 'customerMyCourses.stats.inProgress',
            defaultValue: 'En cours',
          },
          {
            id: 'completedLabel',
            label: 'Label Complétés',
            type: 'text',
            key: 'customerMyCourses.stats.completed',
            defaultValue: 'Complétés',
          },
          {
            id: 'averageProgressLabel',
            label: 'Label Progression moyenne',
            type: 'text',
            key: 'customerMyCourses.stats.averageProgress',
            defaultValue: 'Progression moyenne',
          },
        ],
      },
      {
        id: 'filters',
        name: 'Filtres',
        type: 'content',
        elements: [
          {
            id: 'searchPlaceholder',
            label: 'Placeholder Recherche',
            type: 'text',
            key: 'customerMyCourses.filters.searchPlaceholder',
            defaultValue: 'Rechercher un cours...',
          },
          {
            id: 'filterAll',
            label: 'Filtre Tous',
            type: 'text',
            key: 'customerMyCourses.filters.all',
            defaultValue: 'Tous',
          },
          {
            id: 'filterInProgress',
            label: 'Filtre En cours',
            type: 'text',
            key: 'customerMyCourses.filters.inProgress',
            defaultValue: 'En cours',
          },
          {
            id: 'filterCompleted',
            label: 'Filtre Complétés',
            type: 'text',
            key: 'customerMyCourses.filters.completed',
            defaultValue: 'Complétés',
          },
        ],
      },
      {
        id: 'course',
        name: 'Cours',
        type: 'content',
        elements: [
          {
            id: 'continueButton',
            label: 'Bouton Continuer',
            type: 'text',
            key: 'customerMyCourses.course.continueButton',
            defaultValue: 'Continuer',
          },
          {
            id: 'startButton',
            label: 'Bouton Commencer',
            type: 'text',
            key: 'customerMyCourses.course.startButton',
            defaultValue: 'Commencer',
          },
          {
            id: 'viewButton',
            label: 'Bouton Voir',
            type: 'text',
            key: 'customerMyCourses.course.viewButton',
            defaultValue: 'Voir',
          },
          {
            id: 'progressLabel',
            label: 'Label Progression',
            type: 'text',
            key: 'customerMyCourses.course.progress',
            defaultValue: 'Progression',
          },
          {
            id: 'noCoursesMessage',
            label: 'Message Aucun cours',
            type: 'textarea',
            key: 'customerMyCourses.course.noCourses',
            defaultValue: 'Aucun cours pour le moment',
          },
        ],
      },
    ],
  },
  {
    id: 'customerMyProfile',
    name: 'Mon Profil',
    route: '/account/profile',
    description: 'Personnalisez tous les éléments de la page mon profil',
    icon: User,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'customerMyProfile.header.title',
            defaultValue: 'Mon Profil',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'customerMyProfile.header.subtitle',
            defaultValue: 'Gérez vos informations personnelles et vos adresses',
          },
        ],
      },
      {
        id: 'tabs',
        name: 'Onglets',
        type: 'content',
        elements: [
          {
            id: 'profileTab',
            label: 'Onglet Profil',
            type: 'text',
            key: 'customerMyProfile.tabs.profile',
            defaultValue: 'Profil',
          },
          {
            id: 'addressesTab',
            label: 'Onglet Adresses',
            type: 'text',
            key: 'customerMyProfile.tabs.addresses',
            defaultValue: 'Adresses',
          },
        ],
      },
      {
        id: 'profile',
        name: 'Profil',
        type: 'content',
        elements: [
          {
            id: 'fullNameLabel',
            label: 'Label Nom complet',
            type: 'text',
            key: 'customerMyProfile.profile.fullNameLabel',
            defaultValue: 'Nom complet',
          },
          {
            id: 'emailLabel',
            label: 'Label Email',
            type: 'text',
            key: 'customerMyProfile.profile.emailLabel',
            defaultValue: 'Email',
          },
          {
            id: 'phoneLabel',
            label: 'Label Téléphone',
            type: 'text',
            key: 'customerMyProfile.profile.phoneLabel',
            defaultValue: 'Téléphone',
          },
          {
            id: 'saveButton',
            label: 'Bouton Enregistrer',
            type: 'text',
            key: 'customerMyProfile.profile.saveButton',
            defaultValue: 'Enregistrer',
          },
        ],
      },
      {
        id: 'addresses',
        name: 'Adresses',
        type: 'content',
        elements: [
          {
            id: 'addAddressButton',
            label: 'Bouton Ajouter adresse',
            type: 'text',
            key: 'customerMyProfile.addresses.addButton',
            defaultValue: 'Ajouter une adresse',
          },
          {
            id: 'editButton',
            label: 'Bouton Modifier',
            type: 'text',
            key: 'customerMyProfile.addresses.editButton',
            defaultValue: 'Modifier',
          },
          {
            id: 'deleteButton',
            label: 'Bouton Supprimer',
            type: 'text',
            key: 'customerMyProfile.addresses.deleteButton',
            defaultValue: 'Supprimer',
          },
          {
            id: 'setDefaultButton',
            label: 'Bouton Définir par défaut',
            type: 'text',
            key: 'customerMyProfile.addresses.setDefaultButton',
            defaultValue: 'Définir par défaut',
          },
          {
            id: 'noAddressesMessage',
            label: 'Message Aucune adresse',
            type: 'textarea',
            key: 'customerMyProfile.addresses.noAddresses',
            defaultValue: 'Aucune adresse enregistrée',
          },
        ],
      },
    ],
  },
  {
    id: 'customerMyWishlist',
    name: 'Ma Wishlist',
    route: '/account/wishlist',
    description: 'Personnalisez tous les éléments de la page wishlist',
    icon: Heart,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'customerMyWishlist.header.title',
            defaultValue: 'Ma Wishlist',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'customerMyWishlist.header.subtitle',
            defaultValue: 'Vos produits favoris',
          },
          {
            id: 'shareButton',
            label: 'Bouton Partager',
            type: 'text',
            key: 'customerMyWishlist.header.shareButton',
            defaultValue: 'Partager',
          },
        ],
      },
      {
        id: 'stats',
        name: 'Statistiques',
        type: 'content',
        elements: [
          {
            id: 'totalLabel',
            label: 'Label Total',
            type: 'text',
            key: 'customerMyWishlist.stats.total',
            defaultValue: 'Total',
          },
          {
            id: 'digitalLabel',
            label: 'Label Digital',
            type: 'text',
            key: 'customerMyWishlist.stats.digital',
            defaultValue: 'Digital',
          },
          {
            id: 'physicalLabel',
            label: 'Label Physique',
            type: 'text',
            key: 'customerMyWishlist.stats.physical',
            defaultValue: 'Physique',
          },
          {
            id: 'serviceLabel',
            label: 'Label Service',
            type: 'text',
            key: 'customerMyWishlist.stats.service',
            defaultValue: 'Service',
          },
          {
            id: 'courseLabel',
            label: 'Label Cours',
            type: 'text',
            key: 'customerMyWishlist.stats.course',
            defaultValue: 'Cours',
          },
        ],
      },
      {
        id: 'filters',
        name: 'Filtres',
        type: 'content',
        elements: [
          {
            id: 'searchPlaceholder',
            label: 'Placeholder Recherche',
            type: 'text',
            key: 'customerMyWishlist.filters.searchPlaceholder',
            defaultValue: 'Rechercher dans la wishlist...',
          },
          {
            id: 'filterAll',
            label: 'Filtre Tous',
            type: 'text',
            key: 'customerMyWishlist.filters.all',
            defaultValue: 'Tous',
          },
          {
            id: 'filterDigital',
            label: 'Filtre Digital',
            type: 'text',
            key: 'customerMyWishlist.filters.digital',
            defaultValue: 'Digital',
          },
          {
            id: 'filterPhysical',
            label: 'Filtre Physique',
            type: 'text',
            key: 'customerMyWishlist.filters.physical',
            defaultValue: 'Physique',
          },
          {
            id: 'filterService',
            label: 'Filtre Service',
            type: 'text',
            key: 'customerMyWishlist.filters.service',
            defaultValue: 'Service',
          },
          {
            id: 'filterCourse',
            label: 'Filtre Cours',
            type: 'text',
            key: 'customerMyWishlist.filters.course',
            defaultValue: 'Cours',
          },
        ],
      },
      {
        id: 'actions',
        name: 'Actions',
        type: 'content',
        elements: [
          {
            id: 'addToCartButton',
            label: 'Bouton Ajouter au panier',
            type: 'text',
            key: 'customerMyWishlist.actions.addToCart',
            defaultValue: 'Ajouter au panier',
          },
          {
            id: 'removeButton',
            label: 'Bouton Retirer',
            type: 'text',
            key: 'customerMyWishlist.actions.remove',
            defaultValue: 'Retirer',
          },
          {
            id: 'noWishlistMessage',
            label: 'Message Wishlist vide',
            type: 'textarea',
            key: 'customerMyWishlist.actions.noWishlist',
            defaultValue: 'Aucun produit dans votre wishlist',
          },
        ],
      },
    ],
  },
  {
    id: 'priceStockAlerts',
    name: 'Mes Alertes',
    route: '/account/alerts',
    description: 'Personnalisez tous les éléments de la page mes alertes',
    icon: Bell,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'priceStockAlerts.header.title',
            defaultValue: 'Mes Alertes',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'priceStockAlerts.header.subtitle',
            defaultValue: 'Gérez vos alertes de prix et de stock',
          },
          {
            id: 'refreshButton',
            label: 'Bouton Rafraîchir',
            type: 'text',
            key: 'priceStockAlerts.header.refreshButton',
            defaultValue: 'Rafraîchir',
          },
        ],
      },
      {
        id: 'stats',
        name: 'Statistiques',
        type: 'content',
        elements: [
          {
            id: 'totalLabel',
            label: 'Label Total',
            type: 'text',
            key: 'priceStockAlerts.stats.total',
            defaultValue: 'Total',
          },
          {
            id: 'priceLabel',
            label: 'Label Prix',
            type: 'text',
            key: 'priceStockAlerts.stats.price',
            defaultValue: 'Prix',
          },
          {
            id: 'stockLabel',
            label: 'Label Stock',
            type: 'text',
            key: 'priceStockAlerts.stats.stock',
            defaultValue: 'Stock',
          },
          {
            id: 'priceReachedLabel',
            label: 'Label Prix atteint',
            type: 'text',
            key: 'priceStockAlerts.stats.priceReached',
            defaultValue: 'Prix atteint',
          },
          {
            id: 'stockInStockLabel',
            label: 'Label En stock',
            type: 'text',
            key: 'priceStockAlerts.stats.stockInStock',
            defaultValue: 'En stock',
          },
        ],
      },
      {
        id: 'tabs',
        name: 'Onglets',
        type: 'content',
        elements: [
          {
            id: 'priceTab',
            label: 'Onglet Prix',
            type: 'text',
            key: 'priceStockAlerts.tabs.price',
            defaultValue: 'Alertes Prix',
          },
          {
            id: 'stockTab',
            label: 'Onglet Stock',
            type: 'text',
            key: 'priceStockAlerts.tabs.stock',
            defaultValue: 'Alertes Stock',
          },
        ],
      },
      {
        id: 'actions',
        name: 'Actions',
        type: 'content',
        elements: [
          {
            id: 'deleteButton',
            label: 'Bouton Supprimer',
            type: 'text',
            key: 'priceStockAlerts.actions.delete',
            defaultValue: 'Supprimer',
          },
          {
            id: 'viewProductButton',
            label: 'Bouton Voir produit',
            type: 'text',
            key: 'priceStockAlerts.actions.viewProduct',
            defaultValue: 'Voir produit',
          },
          {
            id: 'noAlertsMessage',
            label: 'Message Aucune alerte',
            type: 'textarea',
            key: 'priceStockAlerts.actions.noAlerts',
            defaultValue: 'Aucune alerte pour le moment',
          },
        ],
      },
    ],
  },
  {
    id: 'customerMyInvoices',
    name: 'Mes Factures',
    route: '/account/invoices',
    description: 'Personnalisez tous les éléments de la page mes factures',
    icon: FileText,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'customerMyInvoices.header.title',
            defaultValue: 'Mes Factures',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'customerMyInvoices.header.subtitle',
            defaultValue: 'Consultez et téléchargez toutes vos factures',
          },
          {
            id: 'refreshButton',
            label: 'Bouton Rafraîchir',
            type: 'text',
            key: 'customerMyInvoices.header.refreshButton',
            defaultValue: 'Rafraîchir',
          },
        ],
      },
      {
        id: 'stats',
        name: 'Statistiques',
        type: 'content',
        elements: [
          {
            id: 'totalLabel',
            label: 'Label Total',
            type: 'text',
            key: 'customerMyInvoices.stats.total',
            defaultValue: 'Total',
          },
          {
            id: 'paidLabel',
            label: 'Label Payées',
            type: 'text',
            key: 'customerMyInvoices.stats.paid',
            defaultValue: 'Payées',
          },
          {
            id: 'pendingLabel',
            label: 'Label En attente',
            type: 'text',
            key: 'customerMyInvoices.stats.pending',
            defaultValue: 'En attente',
          },
          {
            id: 'totalAmountLabel',
            label: 'Label Montant total',
            type: 'text',
            key: 'customerMyInvoices.stats.totalAmount',
            defaultValue: 'Montant total',
          },
        ],
      },
      {
        id: 'filters',
        name: 'Filtres',
        type: 'content',
        elements: [
          {
            id: 'searchPlaceholder',
            label: 'Placeholder Recherche',
            type: 'text',
            key: 'customerMyInvoices.filters.searchPlaceholder',
            defaultValue: 'Rechercher une facture...',
          },
          {
            id: 'filterAll',
            label: 'Filtre Toutes',
            type: 'text',
            key: 'customerMyInvoices.filters.all',
            defaultValue: 'Toutes',
          },
          {
            id: 'filterPaid',
            label: 'Filtre Payées',
            type: 'text',
            key: 'customerMyInvoices.filters.paid',
            defaultValue: 'Payées',
          },
          {
            id: 'filterSent',
            label: 'Filtre Envoyées',
            type: 'text',
            key: 'customerMyInvoices.filters.sent',
            defaultValue: 'Envoyées',
          },
          {
            id: 'filterDraft',
            label: 'Filtre Brouillons',
            type: 'text',
            key: 'customerMyInvoices.filters.draft',
            defaultValue: 'Brouillons',
          },
          {
            id: 'filterOverdue',
            label: 'Filtre Échues',
            type: 'text',
            key: 'customerMyInvoices.filters.overdue',
            defaultValue: 'Échues',
          },
          {
            id: 'filterCancelled',
            label: 'Filtre Annulées',
            type: 'text',
            key: 'customerMyInvoices.filters.cancelled',
            defaultValue: 'Annulées',
          },
        ],
      },
      {
        id: 'invoice',
        name: 'Facture',
        type: 'content',
        elements: [
          {
            id: 'downloadButton',
            label: 'Bouton Télécharger PDF',
            type: 'text',
            key: 'customerMyInvoices.invoice.downloadButton',
            defaultValue: 'Télécharger PDF',
          },
          {
            id: 'invoiceNumberLabel',
            label: 'Label Numéro facture',
            type: 'text',
            key: 'customerMyInvoices.invoice.invoiceNumber',
            defaultValue: 'Facture',
          },
          {
            id: 'statusLabel',
            label: 'Label Statut',
            type: 'text',
            key: 'customerMyInvoices.invoice.status',
            defaultValue: 'Statut',
          },
          {
            id: 'noInvoicesMessage',
            label: 'Message Aucune facture',
            type: 'textarea',
            key: 'customerMyInvoices.invoice.noInvoices',
            defaultValue: 'Aucune facture pour le moment',
          },
        ],
      },
    ],
  },
  {
    id: 'customerMyReturns',
    name: 'Mes Retours',
    route: '/account/returns',
    description: 'Personnalisez tous les éléments de la page mes retours',
    icon: RotateCcw,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'customerMyReturns.header.title',
            defaultValue: 'Mes Retours',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'customerMyReturns.header.subtitle',
            defaultValue: 'Gérez vos demandes de retour et remboursement',
          },
          {
            id: 'refreshButton',
            label: 'Bouton Rafraîchir',
            type: 'text',
            key: 'customerMyReturns.header.refreshButton',
            defaultValue: 'Rafraîchir',
          },
        ],
      },
      {
        id: 'stats',
        name: 'Statistiques',
        type: 'content',
        elements: [
          {
            id: 'totalLabel',
            label: 'Label Total',
            type: 'text',
            key: 'customerMyReturns.stats.total',
            defaultValue: 'Total Retours',
          },
          {
            id: 'inProgressLabel',
            label: 'Label En cours',
            type: 'text',
            key: 'customerMyReturns.stats.inProgress',
            defaultValue: 'En cours',
          },
          {
            id: 'refundedLabel',
            label: 'Label Remboursés',
            type: 'text',
            key: 'customerMyReturns.stats.refunded',
            defaultValue: 'Remboursés',
          },
          {
            id: 'totalRefundedLabel',
            label: 'Label Total remboursé',
            type: 'text',
            key: 'customerMyReturns.stats.totalRefunded',
            defaultValue: 'Total remboursé',
          },
        ],
      },
      {
        id: 'filters',
        name: 'Filtres',
        type: 'content',
        elements: [
          {
            id: 'searchPlaceholder',
            label: 'Placeholder Recherche',
            type: 'text',
            key: 'customerMyReturns.filters.searchPlaceholder',
            defaultValue: 'Rechercher un retour...',
          },
          {
            id: 'filterAll',
            label: 'Filtre Tous',
            type: 'text',
            key: 'customerMyReturns.filters.all',
            defaultValue: 'Tous',
          },
          {
            id: 'filterRequested',
            label: 'Filtre Demandés',
            type: 'text',
            key: 'customerMyReturns.filters.requested',
            defaultValue: 'Demandés',
          },
          {
            id: 'filterApproved',
            label: 'Filtre Approuvés',
            type: 'text',
            key: 'customerMyReturns.filters.approved',
            defaultValue: 'Approuvés',
          },
          {
            id: 'filterRefunded',
            label: 'Filtre Remboursés',
            type: 'text',
            key: 'customerMyReturns.filters.refunded',
            defaultValue: 'Remboursés',
          },
          {
            id: 'filterRejected',
            label: 'Filtre Rejetés',
            type: 'text',
            key: 'customerMyReturns.filters.rejected',
            defaultValue: 'Rejetés',
          },
          {
            id: 'filterCancelled',
            label: 'Filtre Annulés',
            type: 'text',
            key: 'customerMyReturns.filters.cancelled',
            defaultValue: 'Annulés',
          },
        ],
      },
      {
        id: 'return',
        name: 'Retour',
        type: 'content',
        elements: [
          {
            id: 'returnNumberLabel',
            label: 'Label Numéro retour',
            type: 'text',
            key: 'customerMyReturns.return.returnNumber',
            defaultValue: 'Retour',
          },
          {
            id: 'statusLabel',
            label: 'Label Statut',
            type: 'text',
            key: 'customerMyReturns.return.status',
            defaultValue: 'Statut',
          },
          {
            id: 'viewButton',
            label: 'Bouton Voir détails',
            type: 'text',
            key: 'customerMyReturns.return.viewButton',
            defaultValue: 'Voir détails',
          },
          {
            id: 'noReturnsMessage',
            label: 'Message Aucun retour',
            type: 'textarea',
            key: 'customerMyReturns.return.noReturns',
            defaultValue: 'Aucun retour pour le moment',
          },
        ],
      },
    ],
  },
  {
    id: 'customerLoyalty',
    name: 'Programme de Fidélité',
    route: '/account/loyalty',
    description: 'Personnalisez tous les éléments de la page programme de fidélité',
    icon: Award,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'customerLoyalty.header.title',
            defaultValue: 'Programme de Fidélité',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'customerLoyalty.header.subtitle',
            defaultValue:
              'Consultez vos points, échangez des récompenses et suivez votre progression',
          },
        ],
      },
      {
        id: 'points',
        name: 'Points',
        type: 'content',
        elements: [
          {
            id: 'availablePointsLabel',
            label: 'Label Points disponibles',
            type: 'text',
            key: 'customerLoyalty.points.available',
            defaultValue: 'Points disponibles',
          },
          {
            id: 'currentTierLabel',
            label: 'Label Tier actuel',
            type: 'text',
            key: 'customerLoyalty.points.currentTier',
            defaultValue: 'Tier actuel',
          },
          {
            id: 'nextTierLabel',
            label: 'Label Prochain tier',
            type: 'text',
            key: 'customerLoyalty.points.nextTier',
            defaultValue: 'Prochain tier',
          },
          {
            id: 'progressLabel',
            label: 'Label Progression',
            type: 'text',
            key: 'customerLoyalty.points.progress',
            defaultValue: 'Progression',
          },
        ],
      },
      {
        id: 'tabs',
        name: 'Onglets',
        type: 'content',
        elements: [
          {
            id: 'overviewTab',
            label: "Onglet Vue d'ensemble",
            type: 'text',
            key: 'customerLoyalty.tabs.overview',
            defaultValue: "Vue d'ensemble",
          },
          {
            id: 'rewardsTab',
            label: 'Onglet Récompenses',
            type: 'text',
            key: 'customerLoyalty.tabs.rewards',
            defaultValue: 'Récompenses',
          },
          {
            id: 'transactionsTab',
            label: 'Onglet Transactions',
            type: 'text',
            key: 'customerLoyalty.tabs.transactions',
            defaultValue: 'Transactions',
          },
        ],
      },
      {
        id: 'rewards',
        name: 'Récompenses',
        type: 'content',
        elements: [
          {
            id: 'redeemButton',
            label: 'Bouton Échanger',
            type: 'text',
            key: 'customerLoyalty.rewards.redeem',
            defaultValue: 'Échanger',
          },
          {
            id: 'pointsRequiredLabel',
            label: 'Label Points requis',
            type: 'text',
            key: 'customerLoyalty.rewards.pointsRequired',
            defaultValue: 'Points requis',
          },
          {
            id: 'noRewardsMessage',
            label: 'Message Aucune récompense',
            type: 'textarea',
            key: 'customerLoyalty.rewards.noRewards',
            defaultValue: 'Aucune récompense disponible',
          },
        ],
      },
    ],
  },
  {
    id: 'customerMyGiftCards',
    name: 'Mes Cartes Cadeaux',
    route: '/account/gift-cards',
    description: 'Personnalisez tous les éléments de la page mes cartes cadeaux',
    icon: Gift,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'customerMyGiftCards.header.title',
            defaultValue: 'Mes Cartes Cadeaux',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'customerMyGiftCards.header.subtitle',
            defaultValue: 'Gérez vos cartes cadeaux et leur solde',
          },
        ],
      },
      {
        id: 'stats',
        name: 'Statistiques',
        type: 'content',
        elements: [
          {
            id: 'totalBalanceLabel',
            label: 'Label Solde total',
            type: 'text',
            key: 'customerMyGiftCards.stats.totalBalance',
            defaultValue: 'Solde Total',
          },
          {
            id: 'totalCardsLabel',
            label: 'Label Total cartes',
            type: 'text',
            key: 'customerMyGiftCards.stats.totalCards',
            defaultValue: 'Total Cartes',
          },
          {
            id: 'transactionsLabel',
            label: 'Label Transactions',
            type: 'text',
            key: 'customerMyGiftCards.stats.transactions',
            defaultValue: 'Transactions',
          },
        ],
      },
      {
        id: 'giftCard',
        name: 'Carte Cadeau',
        type: 'content',
        elements: [
          {
            id: 'codeLabel',
            label: 'Label Code',
            type: 'text',
            key: 'customerMyGiftCards.giftCard.code',
            defaultValue: 'Code',
          },
          {
            id: 'balanceLabel',
            label: 'Label Solde disponible',
            type: 'text',
            key: 'customerMyGiftCards.giftCard.balance',
            defaultValue: 'Solde disponible',
          },
          {
            id: 'expiresLabel',
            label: 'Label Expire le',
            type: 'text',
            key: 'customerMyGiftCards.giftCard.expires',
            defaultValue: 'Expire le',
          },
          {
            id: 'copyButton',
            label: 'Bouton Copier',
            type: 'text',
            key: 'customerMyGiftCards.giftCard.copyButton',
            defaultValue: 'Copier',
          },
          {
            id: 'activeCardsTitle',
            label: 'Titre Cartes actives',
            type: 'text',
            key: 'customerMyGiftCards.giftCard.activeCardsTitle',
            defaultValue: 'Mes Cartes Cadeaux Actives',
          },
          {
            id: 'activeCardsDescription',
            label: 'Description Cartes actives',
            type: 'textarea',
            key: 'customerMyGiftCards.giftCard.activeCardsDescription',
            defaultValue: 'Vous pouvez utiliser ces cartes lors de vos prochains achats',
          },
          {
            id: 'noGiftCardsMessage',
            label: 'Message Aucune carte',
            type: 'textarea',
            key: 'customerMyGiftCards.giftCard.noGiftCards',
            defaultValue: 'Aucune carte cadeau pour le moment',
          },
        ],
      },
    ],
  },
];
