import {
  BarChart3, CreditCard, Layout, Package, Settings, Store, Tag, Users,
} from 'lucide-react';
import type { PageConfig } from './types';

export const dashboardPagesConfig: PageConfig[] = [
  {
    id: 'dashboard',
    name: 'Dashboard',
    route: '/dashboard',
    description: 'Personnalisez tous les éléments du tableau de bord',
    icon: Layout,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'welcomeMessage',
            label: 'Message de bienvenue',
            type: 'textarea',
            key: 'dashboard.welcome',
            defaultValue: 'Bienvenue sur votre tableau de bord',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'dashboard.subtitle',
            defaultValue: 'Gérez votre boutique en toute simplicité',
          },
          {
            id: 'online',
            label: 'Label En ligne',
            type: 'text',
            key: 'dashboard.online',
            defaultValue: 'En ligne',
          },
          {
            id: 'refresh',
            label: 'Label Actualiser',
            type: 'text',
            key: 'dashboard.refresh',
            defaultValue: 'Actualiser',
          },
          {
            id: 'createStorePrompt',
            label: 'Message Créer boutique',
            type: 'textarea',
            key: 'dashboard.createStorePrompt',
            defaultValue: 'Créez votre première boutique pour commencer',
          },
          {
            id: 'createStoreButton',
            label: 'Bouton Créer boutique',
            type: 'text',
            key: 'dashboard.createStoreButton',
            defaultValue: 'Créer ma boutique',
          },
        ],
      },
    ],
  },
  {
    id: 'dashboardProducts',
    name: 'Dashboard Produits',
    route: '/dashboard/products',
    description: 'Personnalisez tous les éléments de la page produits du dashboard',
    icon: Package,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'dashboardProducts.header.title',
            defaultValue: 'Produits',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'dashboardProducts.header.subtitle',
            defaultValue: 'Gérez vos produits et vendez plus efficacement',
          },
          {
            id: 'refreshButton',
            label: 'Bouton Actualiser',
            type: 'text',
            key: 'dashboardProducts.header.refreshButton',
            defaultValue: 'Actualiser',
          },
          {
            id: 'newProductButton',
            label: 'Bouton Nouveau produit',
            type: 'text',
            key: 'dashboardProducts.header.newProductButton',
            defaultValue: 'Nouveau produit',
          },
        ],
      },
      {
        id: 'empty',
        name: 'État vide',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre état vide',
            type: 'text',
            key: 'dashboardProducts.empty.title',
            defaultValue: 'Aucun produit pour le moment',
          },
          {
            id: 'description',
            label: 'Description état vide',
            type: 'textarea',
            key: 'dashboardProducts.empty.description',
            defaultValue: 'Créez votre premier produit digital ou service pour commencer à vendre',
          },
          {
            id: 'createButton',
            label: 'Bouton Créer',
            type: 'text',
            key: 'dashboardProducts.empty.createButton',
            defaultValue: 'Créer mon premier produit',
          },
          {
            id: 'importButton',
            label: 'Bouton Importer CSV',
            type: 'text',
            key: 'dashboardProducts.empty.importButton',
            defaultValue: 'Importer CSV',
          },
        ],
      },
      {
        id: 'filters',
        name: 'Filtres',
        type: 'content',
        elements: [
          {
            id: 'searchPlaceholder',
            label: 'Placeholder Recherche',
            type: 'text',
            key: 'dashboardProducts.filters.searchPlaceholder',
            defaultValue: 'Rechercher un produit...',
          },
          {
            id: 'filterAll',
            label: 'Filtre Tous',
            type: 'text',
            key: 'dashboardProducts.filters.all',
            defaultValue: 'Tous',
          },
          {
            id: 'filterActive',
            label: 'Filtre Actifs',
            type: 'text',
            key: 'dashboardProducts.filters.active',
            defaultValue: 'Actifs',
          },
          {
            id: 'filterInactive',
            label: 'Filtre Inactifs',
            type: 'text',
            key: 'dashboardProducts.filters.inactive',
            defaultValue: 'Inactifs',
          },
        ],
      },
      {
        id: 'actions',
        name: 'Actions',
        type: 'content',
        elements: [
          {
            id: 'editButton',
            label: 'Bouton Modifier',
            type: 'text',
            key: 'dashboardProducts.actions.edit',
            defaultValue: 'Modifier',
          },
          {
            id: 'deleteButton',
            label: 'Bouton Supprimer',
            type: 'text',
            key: 'dashboardProducts.actions.delete',
            defaultValue: 'Supprimer',
          },
          {
            id: 'duplicateButton',
            label: 'Bouton Dupliquer',
            type: 'text',
            key: 'dashboardProducts.actions.duplicate',
            defaultValue: 'Dupliquer',
          },
        ],
      },
    ],
  },
  {
    id: 'dashboardOrders',
    name: 'Dashboard Commandes',
    route: '/dashboard/orders',
    description: 'Personnalisez tous les éléments de la page commandes du dashboard',
    icon: Package,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'dashboardOrders.header.title',
            defaultValue: 'Commandes',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'dashboardOrders.header.subtitle',
            defaultValue: 'Gérez toutes vos commandes et suivez leurs statuts',
          },
          {
            id: 'exportButton',
            label: 'Bouton Exporter',
            type: 'text',
            key: 'dashboardOrders.header.exportButton',
            defaultValue: 'Exporter',
          },
          {
            id: 'newOrderButton',
            label: 'Bouton Nouvelle commande',
            type: 'text',
            key: 'dashboardOrders.header.newOrderButton',
            defaultValue: 'Nouvelle commande',
          },
        ],
      },
      {
        id: 'stats',
        name: 'Statistiques',
        type: 'content',
        elements: [
          {
            id: 'totalLabel',
            label: 'Label Total',
            type: 'text',
            key: 'dashboardOrders.stats.total',
            defaultValue: 'Total',
          },
          {
            id: 'pendingLabel',
            label: 'Label En attente',
            type: 'text',
            key: 'dashboardOrders.stats.pending',
            defaultValue: 'En attente',
          },
          {
            id: 'completedLabel',
            label: 'Label Terminées',
            type: 'text',
            key: 'dashboardOrders.stats.completed',
            defaultValue: 'Terminées',
          },
          {
            id: 'revenueLabel',
            label: "Label Chiffre d'affaires",
            type: 'text',
            key: 'dashboardOrders.stats.revenue',
            defaultValue: "Chiffre d'affaires",
          },
        ],
      },
      {
        id: 'filters',
        name: 'Filtres',
        type: 'content',
        elements: [
          {
            id: 'searchPlaceholder',
            label: 'Placeholder Recherche',
            type: 'text',
            key: 'dashboardOrders.filters.searchPlaceholder',
            defaultValue: 'Rechercher une commande...',
          },
          {
            id: 'filterAll',
            label: 'Filtre Toutes',
            type: 'text',
            key: 'dashboardOrders.filters.all',
            defaultValue: 'Toutes',
          },
          {
            id: 'filterPending',
            label: 'Filtre En attente',
            type: 'text',
            key: 'dashboardOrders.filters.pending',
            defaultValue: 'En attente',
          },
          {
            id: 'filterCompleted',
            label: 'Filtre Terminées',
            type: 'text',
            key: 'dashboardOrders.filters.completed',
            defaultValue: 'Terminées',
          },
        ],
      },
      {
        id: 'order',
        name: 'Commande',
        type: 'content',
        elements: [
          {
            id: 'viewButton',
            label: 'Bouton Voir',
            type: 'text',
            key: 'dashboardOrders.order.viewButton',
            defaultValue: 'Voir',
          },
          {
            id: 'editButton',
            label: 'Bouton Modifier',
            type: 'text',
            key: 'dashboardOrders.order.editButton',
            defaultValue: 'Modifier',
          },
          {
            id: 'statusLabel',
            label: 'Label Statut',
            type: 'text',
            key: 'dashboardOrders.order.status',
            defaultValue: 'Statut',
          },
          {
            id: 'noOrdersMessage',
            label: 'Message Aucune commande',
            type: 'textarea',
            key: 'dashboardOrders.order.noOrders',
            defaultValue: 'Aucune commande pour le moment',
          },
        ],
      },
    ],
  },
  {
    id: 'dashboardAnalytics',
    name: 'Dashboard Analytics',
    route: '/dashboard/analytics',
    description: 'Personnalisez tous les éléments de la page analytics du dashboard',
    icon: BarChart3,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'dashboardAnalytics.header.title',
            defaultValue: 'Statistiques',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'dashboardAnalytics.header.subtitle',
            defaultValue: "Vue d'ensemble de votre activité",
          },
        ],
      },
      {
        id: 'stats',
        name: 'Statistiques',
        type: 'content',
        elements: [
          {
            id: 'totalRevenueLabel',
            label: 'Label Revenu total',
            type: 'text',
            key: 'dashboardAnalytics.stats.totalRevenue',
            defaultValue: 'Revenu total',
          },
          {
            id: 'totalRevenueDescription',
            label: 'Description Revenu total',
            type: 'text',
            key: 'dashboardAnalytics.stats.totalRevenueDescription',
            defaultValue: 'Total des ventes',
          },
          {
            id: 'ordersLabel',
            label: 'Label Commandes',
            type: 'text',
            key: 'dashboardAnalytics.stats.orders',
            defaultValue: 'Commandes',
          },
          {
            id: 'ordersDescription',
            label: 'Description Commandes',
            type: 'text',
            key: 'dashboardAnalytics.stats.ordersDescription',
            defaultValue: 'Commandes complétées',
          },
          {
            id: 'customersLabel',
            label: 'Label Clients',
            type: 'text',
            key: 'dashboardAnalytics.stats.customers',
            defaultValue: 'Clients',
          },
          {
            id: 'customersDescription',
            label: 'Description Clients',
            type: 'text',
            key: 'dashboardAnalytics.stats.customersDescription',
            defaultValue: 'Clients enregistrés',
          },
          {
            id: 'activeProductsLabel',
            label: 'Label Produits actifs',
            type: 'text',
            key: 'dashboardAnalytics.stats.activeProducts',
            defaultValue: 'Produits actifs',
          },
          {
            id: 'activeProductsDescription',
            label: 'Description Produits actifs',
            type: 'text',
            key: 'dashboardAnalytics.stats.activeProductsDescription',
            defaultValue: 'Sur {total} total',
          },
        ],
      },
      {
        id: 'tabs',
        name: 'Onglets',
        type: 'content',
        elements: [
          {
            id: 'unifiedTab',
            label: 'Onglet Vue unifiée',
            type: 'text',
            key: 'dashboardAnalytics.tabs.unified',
            defaultValue: 'Vue Unifiée',
          },
          {
            id: 'classicTab',
            label: 'Onglet Vue classique',
            type: 'text',
            key: 'dashboardAnalytics.tabs.classic',
            defaultValue: 'Vue Classique',
          },
        ],
      },
      {
        id: 'noStore',
        name: 'Aucune boutique',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre Aucune boutique',
            type: 'text',
            key: 'dashboardAnalytics.noStore.title',
            defaultValue: 'Aucune boutique sélectionnée',
          },
          {
            id: 'description',
            label: 'Description Aucune boutique',
            type: 'textarea',
            key: 'dashboardAnalytics.noStore.description',
            defaultValue:
              'Veuillez sélectionner une boutique ou créer une nouvelle boutique pour voir vos statistiques.',
          },
          {
            id: 'createStoreButton',
            label: 'Bouton Créer boutique',
            type: 'text',
            key: 'dashboardAnalytics.noStore.createStoreButton',
            defaultValue: 'Créer une boutique',
          },
          {
            id: 'backButton',
            label: 'Bouton Retour',
            type: 'text',
            key: 'dashboardAnalytics.noStore.backButton',
            defaultValue: 'Retour au tableau de bord',
          },
        ],
      },
    ],
  },
  {
    id: 'dashboardSettings',
    name: 'Dashboard Paramètres',
    route: '/dashboard/settings',
    description: 'Personnalisez tous les éléments de la page paramètres du dashboard',
    icon: Settings,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'dashboardSettings.header.title',
            defaultValue: 'Paramètres',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'dashboardSettings.header.subtitle',
            defaultValue: 'Gérez vos paramètres et préférences',
          },
        ],
      },
      {
        id: 'tabs',
        name: 'Onglets',
        type: 'content',
        elements: [
          {
            id: 'profileTab',
            label: 'Onglet Profil',
            type: 'text',
            key: 'dashboardSettings.tabs.profile',
            defaultValue: 'Profil',
          },
          {
            id: 'storeTab',
            label: 'Onglet Boutique',
            type: 'text',
            key: 'dashboardSettings.tabs.store',
            defaultValue: 'Boutique',
          },
          {
            id: 'domainTab',
            label: 'Onglet Domaine',
            type: 'text',
            key: 'dashboardSettings.tabs.domain',
            defaultValue: 'Domaine',
          },
          {
            id: 'notificationsTab',
            label: 'Onglet Notifications',
            type: 'text',
            key: 'dashboardSettings.tabs.notifications',
            defaultValue: 'Notifications',
          },
          {
            id: 'importExportTab',
            label: 'Onglet Import/Export',
            type: 'text',
            key: 'dashboardSettings.tabs.importExport',
            defaultValue: 'Import/Export',
          },
          {
            id: 'securityTab',
            label: 'Onglet Sécurité',
            type: 'text',
            key: 'dashboardSettings.tabs.security',
            defaultValue: 'Sécurité',
          },
          {
            id: 'debugTab',
            label: 'Onglet Debug',
            type: 'text',
            key: 'dashboardSettings.tabs.debug',
            defaultValue: 'Debug',
          },
        ],
      },
      {
        id: 'sections',
        name: 'Sections',
        type: 'content',
        elements: [
          {
            id: 'profileTitle',
            label: 'Titre Section Profil',
            type: 'text',
            key: 'dashboardSettings.sections.profileTitle',
            defaultValue: 'Profil',
          },
          {
            id: 'profileDescription',
            label: 'Description Section Profil',
            type: 'textarea',
            key: 'dashboardSettings.sections.profileDescription',
            defaultValue: 'Gérez vos informations personnelles',
          },
          {
            id: 'storeTitle',
            label: 'Titre Section Boutique',
            type: 'text',
            key: 'dashboardSettings.sections.storeTitle',
            defaultValue: 'Boutique',
          },
          {
            id: 'storeDescription',
            label: 'Description Section Boutique',
            type: 'textarea',
            key: 'dashboardSettings.sections.storeDescription',
            defaultValue: 'Configurez les paramètres de votre boutique',
          },
          {
            id: 'notificationsTitle',
            label: 'Titre Section Notifications',
            type: 'text',
            key: 'dashboardSettings.sections.notificationsTitle',
            defaultValue: 'Notifications',
          },
          {
            id: 'notificationsDescription',
            label: 'Description Section Notifications',
            type: 'textarea',
            key: 'dashboardSettings.sections.notificationsDescription',
            defaultValue: 'Gérez vos préférences de notifications',
          },
        ],
      },
    ],
  },
  {
    id: 'dashboardCustomers',
    name: 'Dashboard Clients',
    route: '/dashboard/customers',
    description: 'Personnalisez tous les éléments de la page clients du dashboard',
    icon: Users,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'dashboardCustomers.header.title',
            defaultValue: 'Clients',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'dashboardCustomers.header.subtitle',
            defaultValue: 'Gérez votre base de clients et suivez leurs achats',
          },
          {
            id: 'newCustomerButton',
            label: 'Bouton Nouveau client',
            type: 'text',
            key: 'dashboardCustomers.header.newCustomerButton',
            defaultValue: 'Nouveau client',
          },
        ],
      },
      {
        id: 'stats',
        name: 'Statistiques',
        type: 'content',
        elements: [
          {
            id: 'totalLabel',
            label: 'Label Total',
            type: 'text',
            key: 'dashboardCustomers.stats.total',
            defaultValue: 'Total',
          },
          {
            id: 'totalOrdersLabel',
            label: 'Label Total commandes',
            type: 'text',
            key: 'dashboardCustomers.stats.totalOrders',
            defaultValue: 'Total commandes',
          },
          {
            id: 'totalSpentLabel',
            label: 'Label Total dépensé',
            type: 'text',
            key: 'dashboardCustomers.stats.totalSpent',
            defaultValue: 'Total dépensé',
          },
          {
            id: 'averageSpentLabel',
            label: 'Label Moyenne dépensée',
            type: 'text',
            key: 'dashboardCustomers.stats.averageSpent',
            defaultValue: 'Moyenne dépensée',
          },
        ],
      },
      {
        id: 'filters',
        name: 'Filtres',
        type: 'content',
        elements: [
          {
            id: 'searchPlaceholder',
            label: 'Placeholder Recherche',
            type: 'text',
            key: 'dashboardCustomers.filters.searchPlaceholder',
            defaultValue: 'Rechercher un client...',
          },
          {
            id: 'sortByName',
            label: 'Trier par Nom',
            type: 'text',
            key: 'dashboardCustomers.filters.sortByName',
            defaultValue: 'Nom',
          },
          {
            id: 'sortByDate',
            label: 'Trier par Date',
            type: 'text',
            key: 'dashboardCustomers.filters.sortByDate',
            defaultValue: 'Date',
          },
          {
            id: 'sortByOrders',
            label: 'Trier par Commandes',
            type: 'text',
            key: 'dashboardCustomers.filters.sortByOrders',
            defaultValue: 'Commandes',
          },
          {
            id: 'sortBySpent',
            label: 'Trier par Dépensé',
            type: 'text',
            key: 'dashboardCustomers.filters.sortBySpent',
            defaultValue: 'Dépensé',
          },
        ],
      },
      {
        id: 'customer',
        name: 'Client',
        type: 'content',
        elements: [
          {
            id: 'viewButton',
            label: 'Bouton Voir',
            type: 'text',
            key: 'dashboardCustomers.customer.viewButton',
            defaultValue: 'Voir',
          },
          {
            id: 'editButton',
            label: 'Bouton Modifier',
            type: 'text',
            key: 'dashboardCustomers.customer.editButton',
            defaultValue: 'Modifier',
          },
          {
            id: 'noCustomersMessage',
            label: 'Message Aucun client',
            type: 'textarea',
            key: 'dashboardCustomers.customer.noCustomers',
            defaultValue: 'Aucun client pour le moment',
          },
        ],
      },
    ],
  },
  {
    id: 'dashboardPayments',
    name: 'Dashboard Paiements',
    route: '/dashboard/payments',
    description: 'Personnalisez tous les éléments de la page paiements du dashboard',
    icon: CreditCard,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'dashboardPayments.header.title',
            defaultValue: 'Paiements',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'dashboardPayments.header.subtitle',
            defaultValue: 'Gérez tous vos paiements et transactions',
          },
          {
            id: 'newPaymentButton',
            label: 'Bouton Nouveau paiement',
            type: 'text',
            key: 'dashboardPayments.header.newPaymentButton',
            defaultValue: 'Nouveau paiement',
          },
          {
            id: 'exportButton',
            label: 'Bouton Exporter',
            type: 'text',
            key: 'dashboardPayments.header.exportButton',
            defaultValue: 'Exporter',
          },
        ],
      },
      {
        id: 'tabs',
        name: 'Onglets',
        type: 'content',
        elements: [
          {
            id: 'allTab',
            label: 'Onglet Tous',
            type: 'text',
            key: 'dashboardPayments.tabs.all',
            defaultValue: 'Tous',
          },
          {
            id: 'completedTab',
            label: 'Onglet Complétés',
            type: 'text',
            key: 'dashboardPayments.tabs.completed',
            defaultValue: 'Complétés',
          },
          {
            id: 'pendingTab',
            label: 'Onglet En attente',
            type: 'text',
            key: 'dashboardPayments.tabs.pending',
            defaultValue: 'En attente',
          },
          {
            id: 'failedTab',
            label: 'Onglet Échoués',
            type: 'text',
            key: 'dashboardPayments.tabs.failed',
            defaultValue: 'Échoués',
          },
        ],
      },
      {
        id: 'payment',
        name: 'Paiement',
        type: 'content',
        elements: [
          {
            id: 'viewButton',
            label: 'Bouton Voir',
            type: 'text',
            key: 'dashboardPayments.payment.viewButton',
            defaultValue: 'Voir',
          },
          {
            id: 'editButton',
            label: 'Bouton Modifier',
            type: 'text',
            key: 'dashboardPayments.payment.editButton',
            defaultValue: 'Modifier',
          },
          {
            id: 'deleteButton',
            label: 'Bouton Supprimer',
            type: 'text',
            key: 'dashboardPayments.payment.deleteButton',
            defaultValue: 'Supprimer',
          },
          {
            id: 'statusCompleted',
            label: 'Statut Complété',
            type: 'text',
            key: 'dashboardPayments.payment.statusCompleted',
            defaultValue: 'Complété',
          },
          {
            id: 'statusPending',
            label: 'Statut En attente',
            type: 'text',
            key: 'dashboardPayments.payment.statusPending',
            defaultValue: 'En attente',
          },
          {
            id: 'statusFailed',
            label: 'Statut Échoué',
            type: 'text',
            key: 'dashboardPayments.payment.statusFailed',
            defaultValue: 'Échoué',
          },
          {
            id: 'noPaymentsMessage',
            label: 'Message Aucun paiement',
            type: 'textarea',
            key: 'dashboardPayments.payment.noPayments',
            defaultValue: 'Aucun paiement pour le moment',
          },
        ],
      },
    ],
  },
  {
    id: 'dashboardPromotions',
    name: 'Dashboard Promotions',
    route: '/dashboard/promotions',
    description: 'Personnalisez tous les éléments de la page promotions du dashboard',
    icon: Tag,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'dashboardPromotions.header.title',
            defaultValue: 'Promotions',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'dashboardPromotions.header.subtitle',
            defaultValue: 'Gérez vos codes promo et réductions',
          },
          {
            id: 'newPromotionButton',
            label: 'Bouton Nouvelle promotion',
            type: 'text',
            key: 'dashboardPromotions.header.newPromotionButton',
            defaultValue: 'Nouvelle promotion',
          },
        ],
      },
      {
        id: 'stats',
        name: 'Statistiques',
        type: 'content',
        elements: [
          {
            id: 'totalLabel',
            label: 'Label Total',
            type: 'text',
            key: 'dashboardPromotions.stats.total',
            defaultValue: 'Total',
          },
          {
            id: 'activeLabel',
            label: 'Label Actives',
            type: 'text',
            key: 'dashboardPromotions.stats.active',
            defaultValue: 'Actives',
          },
          {
            id: 'totalUsesLabel',
            label: 'Label Total utilisations',
            type: 'text',
            key: 'dashboardPromotions.stats.totalUses',
            defaultValue: 'Total utilisations',
          },
          {
            id: 'averageDiscountLabel',
            label: 'Label Remise moyenne',
            type: 'text',
            key: 'dashboardPromotions.stats.averageDiscount',
            defaultValue: 'Remise moyenne',
          },
        ],
      },
      {
        id: 'filters',
        name: 'Filtres',
        type: 'content',
        elements: [
          {
            id: 'searchPlaceholder',
            label: 'Placeholder Recherche',
            type: 'text',
            key: 'dashboardPromotions.filters.searchPlaceholder',
            defaultValue: 'Rechercher une promotion...',
          },
          {
            id: 'filterAll',
            label: 'Filtre Toutes',
            type: 'text',
            key: 'dashboardPromotions.filters.all',
            defaultValue: 'Toutes',
          },
          {
            id: 'filterActive',
            label: 'Filtre Actives',
            type: 'text',
            key: 'dashboardPromotions.filters.active',
            defaultValue: 'Actives',
          },
          {
            id: 'filterInactive',
            label: 'Filtre Inactives',
            type: 'text',
            key: 'dashboardPromotions.filters.inactive',
            defaultValue: 'Inactives',
          },
        ],
      },
      {
        id: 'promotion',
        name: 'Promotion',
        type: 'content',
        elements: [
          {
            id: 'codeLabel',
            label: 'Label Code',
            type: 'text',
            key: 'dashboardPromotions.promotion.code',
            defaultValue: 'Code',
          },
          {
            id: 'discountLabel',
            label: 'Label Remise',
            type: 'text',
            key: 'dashboardPromotions.promotion.discount',
            defaultValue: 'Remise',
          },
          {
            id: 'usesLabel',
            label: 'Label Utilisations',
            type: 'text',
            key: 'dashboardPromotions.promotion.uses',
            defaultValue: 'Utilisations',
          },
          {
            id: 'noPromotionsMessage',
            label: 'Message Aucune promotion',
            type: 'textarea',
            key: 'dashboardPromotions.promotion.noPromotions',
            defaultValue: 'Aucune promotion pour le moment',
          },
        ],
      },
    ],
  },
  {
    id: 'dashboardStore',
    name: 'Dashboard Boutique',
    route: '/dashboard/store',
    description: 'Personnalisez tous les éléments de la page boutique du dashboard',
    icon: Store,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'dashboardStore.header.title',
            defaultValue: 'Boutique',
          },
          {
            id: 'viewStoreButton',
            label: 'Bouton Voir la boutique',
            type: 'text',
            key: 'dashboardStore.header.viewStoreButton',
            defaultValue: 'Voir la boutique',
          },
        ],
      },
      {
        id: 'tabs',
        name: 'Onglets',
        type: 'content',
        elements: [
          {
            id: 'manageTab',
            label: 'Onglet Gérer',
            type: 'text',
            key: 'dashboardStore.tabs.manage',
            defaultValue: 'Gérer',
          },
          {
            id: 'createTab',
            label: 'Onglet Créer',
            type: 'text',
            key: 'dashboardStore.tabs.create',
            defaultValue: 'Créer',
          },
        ],
      },
      {
        id: 'empty',
        name: 'État vide',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre état vide',
            type: 'text',
            key: 'dashboardStore.empty.title',
            defaultValue: 'Aucune boutique',
          },
          {
            id: 'description',
            label: 'Description état vide',
            type: 'textarea',
            key: 'dashboardStore.empty.description',
            defaultValue: 'Créez votre première boutique pour commencer à vendre',
          },
          {
            id: 'createButton',
            label: 'Bouton Créer boutique',
            type: 'text',
            key: 'dashboardStore.empty.createButton',
            defaultValue: 'Créer ma boutique',
          },
        ],
      },
      {
        id: 'store',
        name: 'Boutique',
        type: 'content',
        elements: [
          {
            id: 'nameLabel',
            label: 'Label Nom',
            type: 'text',
            key: 'dashboardStore.store.name',
            defaultValue: 'Nom',
          },
          {
            id: 'slugLabel',
            label: 'Label Slug',
            type: 'text',
            key: 'dashboardStore.store.slug',
            defaultValue: 'Slug',
          },
          {
            id: 'descriptionLabel',
            label: 'Label Description',
            type: 'text',
            key: 'dashboardStore.store.description',
            defaultValue: 'Description',
          },
          {
            id: 'statusLabel',
            label: 'Label Statut',
            type: 'text',
            key: 'dashboardStore.store.status',
            defaultValue: 'Statut',
          },
        ],
      },
    ],
  },
];
