import {
  Briefcase, Calendar, Download, GraduationCap, Layers, Package, PenTool, TrendingUp,
} from 'lucide-react';
import type { PageConfig } from './types';

export const productsPagesConfig: PageConfig[] = [
  {
    id: 'affiliateDashboard',
    name: 'Tableau de bord affilié',
    route: '/affiliate/dashboard',
    description: 'Personnalisez tous les éléments du tableau de bord des affiliés',
    icon: TrendingUp,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'affiliateDashboard.title',
            defaultValue: 'Tableau de bord affilié',
          },
          {
            id: 'welcomeMessage',
            label: 'Message de bienvenue',
            type: 'textarea',
            key: 'affiliateDashboard.welcome',
            defaultValue: 'Bienvenue, {name} • Code : {code}',
          },
          {
            id: 'newLinkButton',
            label: 'Bouton Nouveau lien',
            type: 'text',
            key: 'affiliateDashboard.newLinkButton',
            defaultValue: 'Nouveau lien',
          },
        ],
      },
      {
        id: 'stats',
        name: 'Statistiques',
        type: 'content',
        elements: [
          {
            id: 'clicksLabel',
            label: 'Label Clics totaux',
            type: 'text',
            key: 'affiliateDashboard.stats.clicks',
            defaultValue: 'Clics totaux',
          },
          {
            id: 'salesLabel',
            label: 'Label Ventes générées',
            type: 'text',
            key: 'affiliateDashboard.stats.sales',
            defaultValue: 'Ventes générées',
          },
          {
            id: 'revenueLabel',
            label: 'Label CA généré',
            type: 'text',
            key: 'affiliateDashboard.stats.revenue',
            defaultValue: 'CA généré',
          },
          {
            id: 'earningsLabel',
            label: 'Label Gains totaux',
            type: 'text',
            key: 'affiliateDashboard.stats.earnings',
            defaultValue: 'Gains totaux',
          },
          {
            id: 'balanceLabel',
            label: 'Label Solde disponible',
            type: 'text',
            key: 'affiliateDashboard.stats.balance',
            defaultValue: 'Solde disponible',
          },
          {
            id: 'conversionRateLabel',
            label: 'Label Taux de conversion',
            type: 'text',
            key: 'affiliateDashboard.stats.conversionRate',
            defaultValue: 'Taux de conversion',
          },
        ],
      },
      {
        id: 'links',
        name: 'Mes liens',
        type: 'content',
        elements: [
          {
            id: 'tabTitle',
            label: 'Titre onglet Mes liens',
            type: 'text',
            key: 'affiliateDashboard.links.title',
            defaultValue: "Mes liens d'affiliation",
          },
          {
            id: 'createLinkButton',
            label: 'Bouton Créer un lien',
            type: 'text',
            key: 'affiliateDashboard.links.createButton',
            defaultValue: 'Créer un lien',
          },
          {
            id: 'noLinksMessage',
            label: 'Message Aucun lien',
            type: 'textarea',
            key: 'affiliateDashboard.links.noLinks',
            defaultValue: "Aucun lien d'affiliation pour le moment",
          },
          {
            id: 'copyButton',
            label: 'Bouton Copier',
            type: 'text',
            key: 'affiliateDashboard.links.copyButton',
            defaultValue: 'Copier',
          },
          {
            id: 'openButton',
            label: 'Bouton Ouvrir',
            type: 'text',
            key: 'affiliateDashboard.links.openButton',
            defaultValue: 'Ouvrir',
          },
          {
            id: 'clicksLabel',
            label: 'Label Clics',
            type: 'text',
            key: 'affiliateDashboard.links.clicks',
            defaultValue: 'Clics',
          },
          {
            id: 'salesLabel',
            label: 'Label Ventes',
            type: 'text',
            key: 'affiliateDashboard.links.sales',
            defaultValue: 'Ventes',
          },
          {
            id: 'revenueLabel',
            label: 'Label CA généré',
            type: 'text',
            key: 'affiliateDashboard.links.revenue',
            defaultValue: 'CA généré',
          },
          {
            id: 'commissionLabel',
            label: 'Label Commission',
            type: 'text',
            key: 'affiliateDashboard.links.commission',
            defaultValue: 'Commission',
          },
          {
            id: 'conversionLabel',
            label: 'Label Conversion',
            type: 'text',
            key: 'affiliateDashboard.links.conversion',
            defaultValue: 'Conversion',
          },
        ],
      },
      {
        id: 'commissions',
        name: 'Commissions',
        type: 'content',
        elements: [
          {
            id: 'tabTitle',
            label: 'Titre onglet Commissions',
            type: 'text',
            key: 'affiliateDashboard.commissions.title',
            defaultValue: 'Mes commissions',
          },
          {
            id: 'pendingLabel',
            label: 'Label En attente',
            type: 'text',
            key: 'affiliateDashboard.commissions.pending',
            defaultValue: 'En attente',
          },
          {
            id: 'approvedLabel',
            label: 'Label Approuvées',
            type: 'text',
            key: 'affiliateDashboard.commissions.approved',
            defaultValue: 'Approuvées',
          },
          {
            id: 'paidLabel',
            label: 'Label Payées',
            type: 'text',
            key: 'affiliateDashboard.commissions.paid',
            defaultValue: 'Payées',
          },
          {
            id: 'rejectedLabel',
            label: 'Label Rejetées',
            type: 'text',
            key: 'affiliateDashboard.commissions.rejected',
            defaultValue: 'Rejetées',
          },
          {
            id: 'noCommissionsMessage',
            label: 'Message Aucune commission',
            type: 'textarea',
            key: 'affiliateDashboard.commissions.noCommissions',
            defaultValue: 'Aucune commission pour le moment',
          },
        ],
      },
      {
        id: 'withdrawals',
        name: 'Retraits',
        type: 'content',
        elements: [
          {
            id: 'tabTitle',
            label: 'Titre onglet Retraits',
            type: 'text',
            key: 'affiliateDashboard.withdrawals.title',
            defaultValue: 'Mes retraits',
          },
          {
            id: 'requestButton',
            label: 'Bouton Demander un retrait',
            type: 'text',
            key: 'affiliateDashboard.withdrawals.requestButton',
            defaultValue: 'Demander un retrait',
          },
          {
            id: 'minimumAmount',
            label: 'Message Montant minimum',
            type: 'textarea',
            key: 'affiliateDashboard.withdrawals.minimumAmount',
            defaultValue: 'Montant minimum pour retrait : {amount}',
          },
          {
            id: 'noWithdrawalsMessage',
            label: 'Message Aucun retrait',
            type: 'textarea',
            key: 'affiliateDashboard.withdrawals.noWithdrawals',
            defaultValue: 'Aucun retrait pour le moment',
          },
        ],
      },
      {
        id: 'registration',
        name: 'Inscription',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre page inscription',
            type: 'text',
            key: 'affiliateDashboard.registration.title',
            defaultValue: "Rejoignez notre programme d'affiliation",
          },
          {
            id: 'description',
            label: 'Description programme',
            type: 'textarea',
            key: 'affiliateDashboard.registration.description',
            defaultValue: 'Gagnez des commissions en promouvant nos produits',
          },
          {
            id: 'registerButton',
            label: 'Bouton Devenir affilié',
            type: 'text',
            key: 'affiliateDashboard.registration.registerButton',
            defaultValue: 'Devenir affilié',
          },
        ],
      },
    ],
  },
  {
    id: 'serviceDetail',
    name: 'Détail Service',
    route: '/service/:serviceId',
    description: "Personnalisez tous les éléments de la page de détail d'un service",
    icon: Calendar,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'backButton',
            label: 'Bouton Retour',
            type: 'text',
            key: 'serviceDetail.header.backButton',
            defaultValue: 'Retour',
          },
          {
            id: 'shareButton',
            label: 'Bouton Partager',
            type: 'text',
            key: 'serviceDetail.header.shareButton',
            defaultValue: 'Partager',
          },
          {
            id: 'wishlistButton',
            label: 'Bouton Wishlist',
            type: 'text',
            key: 'serviceDetail.header.wishlistButton',
            defaultValue: 'Ajouter à la wishlist',
          },
        ],
      },
      {
        id: 'booking',
        name: 'Réservation',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre Réservation',
            type: 'text',
            key: 'serviceDetail.booking.title',
            defaultValue: 'Réserver ce service',
          },
          {
            id: 'dateLabel',
            label: 'Label Date',
            type: 'text',
            key: 'serviceDetail.booking.dateLabel',
            defaultValue: 'Sélectionner une date',
          },
          {
            id: 'timeLabel',
            label: 'Label Heure',
            type: 'text',
            key: 'serviceDetail.booking.timeLabel',
            defaultValue: 'Sélectionner un créneau',
          },
          {
            id: 'participantsLabel',
            label: 'Label Participants',
            type: 'text',
            key: 'serviceDetail.booking.participantsLabel',
            defaultValue: 'Nombre de participants',
          },
          {
            id: 'bookButton',
            label: 'Bouton Réserver',
            type: 'text',
            key: 'serviceDetail.booking.bookButton',
            defaultValue: 'Réserver maintenant',
          },
          {
            id: 'bookingMessage',
            label: 'Message Réservation',
            type: 'textarea',
            key: 'serviceDetail.booking.message',
            defaultValue: 'Veuillez sélectionner une date et un créneau horaire',
          },
        ],
      },
      {
        id: 'info',
        name: 'Informations',
        type: 'content',
        elements: [
          {
            id: 'durationLabel',
            label: 'Label Durée',
            type: 'text',
            key: 'serviceDetail.info.durationLabel',
            defaultValue: 'Durée',
          },
          {
            id: 'locationLabel',
            label: 'Label Lieu',
            type: 'text',
            key: 'serviceDetail.info.locationLabel',
            defaultValue: 'Lieu',
          },
          {
            id: 'capacityLabel',
            label: 'Label Capacité',
            type: 'text',
            key: 'serviceDetail.info.capacityLabel',
            defaultValue: 'Capacité',
          },
          {
            id: 'priceLabel',
            label: 'Label Prix',
            type: 'text',
            key: 'serviceDetail.info.priceLabel',
            defaultValue: 'Prix',
          },
        ],
      },
      {
        id: 'tabs',
        name: 'Onglets',
        type: 'content',
        elements: [
          {
            id: 'descriptionTab',
            label: 'Onglet Description',
            type: 'text',
            key: 'serviceDetail.tabs.description',
            defaultValue: 'Description',
          },
          {
            id: 'reviewsTab',
            label: 'Onglet Avis',
            type: 'text',
            key: 'serviceDetail.tabs.reviews',
            defaultValue: 'Avis',
          },
          {
            id: 'recommendationsTab',
            label: 'Onglet Recommandations',
            type: 'text',
            key: 'serviceDetail.tabs.recommendations',
            defaultValue: 'Recommandations',
          },
        ],
      },
    ],
  },
  {
    id: 'serviceManagement',
    name: 'Gestion Services',
    route: '/dashboard/service-management',
    description: 'Personnalisez tous les éléments de la page de gestion des services',
    icon: Briefcase,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'text',
            key: 'serviceManagement.header.title',
            defaultValue: 'Gestion des Services',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'serviceManagement.header.subtitle',
            defaultValue: 'Gérez vos services, calendrier et disponibilités',
          },
        ],
      },
      {
        id: 'stats',
        name: 'Statistiques',
        type: 'content',
        elements: [
          {
            id: 'bookingsLabel',
            label: 'Label Réservations',
            type: 'text',
            key: 'serviceManagement.stats.bookings',
            defaultValue: 'Réservations',
          },
          {
            id: 'staffLabel',
            label: 'Label Personnel',
            type: 'text',
            key: 'serviceManagement.stats.staff',
            defaultValue: 'Personnel actif',
          },
          {
            id: 'conflictsLabel',
            label: 'Label Conflits',
            type: 'text',
            key: 'serviceManagement.stats.conflicts',
            defaultValue: 'Conflits détectés',
          },
        ],
      },
      {
        id: 'tabs',
        name: 'Onglets',
        type: 'content',
        elements: [
          {
            id: 'calendarTab',
            label: 'Onglet Calendrier',
            type: 'text',
            key: 'serviceManagement.tabs.calendar',
            defaultValue: 'Calendrier',
          },
          {
            id: 'availabilityTab',
            label: 'Onglet Disponibilité',
            type: 'text',
            key: 'serviceManagement.tabs.availability',
            defaultValue: 'Disponibilité',
          },
          {
            id: 'conflictsTab',
            label: 'Onglet Conflits',
            type: 'text',
            key: 'serviceManagement.tabs.conflicts',
            defaultValue: 'Conflits',
          },
        ],
      },
    ],
  },
  {
    id: 'artistProductDetail',
    name: "Œuvre d'Artiste",
    route: '/artist/:productId',
    description: "Personnalisez tous les éléments de la page de détail d'une œuvre d'artiste",
    icon: PenTool,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'backButton',
            label: 'Bouton Retour',
            type: 'text',
            key: 'artistProductDetail.header.backButton',
            defaultValue: 'Retour',
          },
          {
            id: 'shareButton',
            label: 'Bouton Partager',
            type: 'text',
            key: 'artistProductDetail.header.shareButton',
            defaultValue: 'Partager',
          },
          {
            id: 'wishlistButton',
            label: 'Bouton Wishlist',
            type: 'text',
            key: 'artistProductDetail.header.wishlistButton',
            defaultValue: 'Ajouter à la wishlist',
          },
        ],
      },
      {
        id: 'purchase',
        name: 'Achat',
        type: 'content',
        elements: [
          {
            id: 'quantityLabel',
            label: 'Label Quantité',
            type: 'text',
            key: 'artistProductDetail.purchase.quantityLabel',
            defaultValue: 'Quantité',
          },
          {
            id: 'addToCartButton',
            label: 'Bouton Ajouter au panier',
            type: 'text',
            key: 'artistProductDetail.purchase.addToCartButton',
            defaultValue: 'Ajouter au panier',
          },
          {
            id: 'buyNowButton',
            label: 'Bouton Acheter maintenant',
            type: 'text',
            key: 'artistProductDetail.purchase.buyNowButton',
            defaultValue: 'Acheter maintenant',
          },
          {
            id: 'priceLabel',
            label: 'Label Prix',
            type: 'text',
            key: 'artistProductDetail.purchase.priceLabel',
            defaultValue: 'Prix',
          },
        ],
      },
      {
        id: 'certificate',
        name: 'Certificat',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre Certificat',
            type: 'text',
            key: 'artistProductDetail.certificate.title',
            defaultValue: "Certificat d'authenticité",
          },
          {
            id: 'description',
            label: 'Description Certificat',
            type: 'textarea',
            key: 'artistProductDetail.certificate.description',
            defaultValue: "Cette œuvre est accompagnée d'un certificat d'authenticité",
          },
          {
            id: 'artistLabel',
            label: 'Label Artiste',
            type: 'text',
            key: 'artistProductDetail.certificate.artistLabel',
            defaultValue: 'Artiste',
          },
          {
            id: 'yearLabel',
            label: 'Label Année',
            type: 'text',
            key: 'artistProductDetail.certificate.yearLabel',
            defaultValue: 'Année',
          },
        ],
      },
      {
        id: 'shipping',
        name: 'Livraison',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre Livraison',
            type: 'text',
            key: 'artistProductDetail.shipping.title',
            defaultValue: 'Informations de livraison',
          },
          {
            id: 'shippingLabel',
            label: 'Label Livraison',
            type: 'text',
            key: 'artistProductDetail.shipping.shippingLabel',
            defaultValue: 'Livraison',
          },
          {
            id: 'handlingLabel',
            label: 'Label Manutention',
            type: 'text',
            key: 'artistProductDetail.shipping.handlingLabel',
            defaultValue: 'Manutention spéciale',
          },
        ],
      },
      {
        id: 'tabs',
        name: 'Onglets',
        type: 'content',
        elements: [
          {
            id: 'descriptionTab',
            label: 'Onglet Description',
            type: 'text',
            key: 'artistProductDetail.tabs.description',
            defaultValue: 'Description',
          },
          {
            id: 'reviewsTab',
            label: 'Onglet Avis',
            type: 'text',
            key: 'artistProductDetail.tabs.reviews',
            defaultValue: 'Avis',
          },
          {
            id: 'certificateTab',
            label: 'Onglet Certificat',
            type: 'text',
            key: 'artistProductDetail.tabs.certificate',
            defaultValue: 'Certificat',
          },
        ],
      },
    ],
  },
  {
    id: 'digitalProductDetail',
    name: 'Détail Produit Digital',
    route: '/digital/:productId',
    description: "Personnalisez tous les éléments de la page de détail d'un produit digital",
    icon: Download,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'backButton',
            label: 'Bouton Retour',
            type: 'text',
            key: 'digitalProductDetail.header.backButton',
            defaultValue: 'Retour',
          },
          {
            id: 'compareButton',
            label: 'Bouton Comparer',
            type: 'text',
            key: 'digitalProductDetail.header.compareButton',
            defaultValue: 'Comparer',
          },
        ],
      },
      {
        id: 'purchase',
        name: 'Achat',
        type: 'content',
        elements: [
          {
            id: 'buyButton',
            label: 'Bouton Acheter',
            type: 'text',
            key: 'digitalProductDetail.purchase.buyButton',
            defaultValue: 'Acheter maintenant',
          },
          {
            id: 'downloadButton',
            label: 'Bouton Télécharger',
            type: 'text',
            key: 'digitalProductDetail.purchase.downloadButton',
            defaultValue: 'Télécharger',
          },
          {
            id: 'priceLabel',
            label: 'Label Prix',
            type: 'text',
            key: 'digitalProductDetail.purchase.priceLabel',
            defaultValue: 'Prix',
          },
          {
            id: 'licenseLabel',
            label: 'Label Licence',
            type: 'text',
            key: 'digitalProductDetail.purchase.licenseLabel',
            defaultValue: 'Licence',
          },
        ],
      },
      {
        id: 'files',
        name: 'Fichiers',
        type: 'content',
        elements: [
          {
            id: 'filesTitle',
            label: 'Titre Fichiers',
            type: 'text',
            key: 'digitalProductDetail.files.title',
            defaultValue: 'Fichiers inclus',
          },
          {
            id: 'fileSizeLabel',
            label: 'Label Taille',
            type: 'text',
            key: 'digitalProductDetail.files.sizeLabel',
            defaultValue: 'Taille',
          },
          {
            id: 'fileFormatLabel',
            label: 'Label Format',
            type: 'text',
            key: 'digitalProductDetail.files.formatLabel',
            defaultValue: 'Format',
          },
          {
            id: 'downloadCountLabel',
            label: 'Label Téléchargements',
            type: 'text',
            key: 'digitalProductDetail.files.downloadCountLabel',
            defaultValue: 'Téléchargements',
          },
        ],
      },
      {
        id: 'tabs',
        name: 'Onglets',
        type: 'content',
        elements: [
          {
            id: 'descriptionTab',
            label: 'Onglet Description',
            type: 'text',
            key: 'digitalProductDetail.tabs.description',
            defaultValue: 'Description',
          },
          {
            id: 'filesTab',
            label: 'Onglet Fichiers',
            type: 'text',
            key: 'digitalProductDetail.tabs.files',
            defaultValue: 'Fichiers détails',
          },
          {
            id: 'reviewsTab',
            label: 'Onglet Avis',
            type: 'text',
            key: 'digitalProductDetail.tabs.reviews',
            defaultValue: 'Avis',
          },
          {
            id: 'faqsTab',
            label: 'Onglet FAQs',
            type: 'text',
            key: 'digitalProductDetail.tabs.faqs',
            defaultValue: 'FAQs',
          },
        ],
      },
    ],
  },
  {
    id: 'physicalProductDetail',
    name: 'Détail Produit Physique',
    route: '/physical/:productId',
    description: "Personnalisez tous les éléments de la page de détail d'un produit physique",
    icon: Package,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'backButton',
            label: 'Bouton Retour',
            type: 'text',
            key: 'physicalProductDetail.header.backButton',
            defaultValue: 'Retour',
          },
          {
            id: 'shareButton',
            label: 'Bouton Partager',
            type: 'text',
            key: 'physicalProductDetail.header.shareButton',
            defaultValue: 'Partager',
          },
          {
            id: 'wishlistButton',
            label: 'Bouton Wishlist',
            type: 'text',
            key: 'physicalProductDetail.header.wishlistButton',
            defaultValue: 'Ajouter à la wishlist',
          },
        ],
      },
      {
        id: 'purchase',
        name: 'Achat',
        type: 'content',
        elements: [
          {
            id: 'quantityLabel',
            label: 'Label Quantité',
            type: 'text',
            key: 'physicalProductDetail.purchase.quantityLabel',
            defaultValue: 'Quantité',
          },
          {
            id: 'addToCartButton',
            label: 'Bouton Ajouter au panier',
            type: 'text',
            key: 'physicalProductDetail.purchase.addToCartButton',
            defaultValue: 'Ajouter au panier',
          },
          {
            id: 'buyNowButton',
            label: 'Bouton Acheter maintenant',
            type: 'text',
            key: 'physicalProductDetail.purchase.buyNowButton',
            defaultValue: 'Acheter maintenant',
          },
          {
            id: 'priceLabel',
            label: 'Label Prix',
            type: 'text',
            key: 'physicalProductDetail.purchase.priceLabel',
            defaultValue: 'Prix',
          },
          {
            id: 'stockLabel',
            label: 'Label Stock',
            type: 'text',
            key: 'physicalProductDetail.purchase.stockLabel',
            defaultValue: 'Stock',
          },
        ],
      },
      {
        id: 'variants',
        name: 'Variantes',
        type: 'content',
        elements: [
          {
            id: 'variantLabel',
            label: 'Label Variante',
            type: 'text',
            key: 'physicalProductDetail.variants.variantLabel',
            defaultValue: 'Variante',
          },
          {
            id: 'sizeLabel',
            label: 'Label Taille',
            type: 'text',
            key: 'physicalProductDetail.variants.sizeLabel',
            defaultValue: 'Taille',
          },
          {
            id: 'colorLabel',
            label: 'Label Couleur',
            type: 'text',
            key: 'physicalProductDetail.variants.colorLabel',
            defaultValue: 'Couleur',
          },
        ],
      },
      {
        id: 'shipping',
        name: 'Livraison',
        type: 'content',
        elements: [
          {
            id: 'shippingTitle',
            label: 'Titre Livraison',
            type: 'text',
            key: 'physicalProductDetail.shipping.title',
            defaultValue: 'Informations de livraison',
          },
          {
            id: 'shippingLabel',
            label: 'Label Livraison',
            type: 'text',
            key: 'physicalProductDetail.shipping.shippingLabel',
            defaultValue: 'Livraison',
          },
          {
            id: 'dimensionsLabel',
            label: 'Label Dimensions',
            type: 'text',
            key: 'physicalProductDetail.shipping.dimensionsLabel',
            defaultValue: 'Dimensions',
          },
          {
            id: 'weightLabel',
            label: 'Label Poids',
            type: 'text',
            key: 'physicalProductDetail.shipping.weightLabel',
            defaultValue: 'Poids',
          },
        ],
      },
      {
        id: 'tabs',
        name: 'Onglets',
        type: 'content',
        elements: [
          {
            id: 'descriptionTab',
            label: 'Onglet Description',
            type: 'text',
            key: 'physicalProductDetail.tabs.description',
            defaultValue: 'Description',
          },
          {
            id: 'specificationsTab',
            label: 'Onglet Spécifications',
            type: 'text',
            key: 'physicalProductDetail.tabs.specifications',
            defaultValue: 'Spécifications',
          },
          {
            id: 'reviewsTab',
            label: 'Onglet Avis',
            type: 'text',
            key: 'physicalProductDetail.tabs.reviews',
            defaultValue: 'Avis',
          },
        ],
      },
    ],
  },
  {
    id: 'courseDetail',
    name: 'Détail Cours',
    route: '/courses/:slug',
    description: "Personnalisez tous les éléments de la page de détail d'un cours",
    icon: GraduationCap,
    sections: [
      {
        id: 'hero',
        name: 'Section Hero',
        type: 'content',
        elements: [
          {
            id: 'categoryLabel',
            label: 'Label Catégorie',
            type: 'text',
            key: 'courseDetail.hero.categoryLabel',
            defaultValue: 'Catégorie',
          },
          {
            id: 'ratingLabel',
            label: 'Label Note',
            type: 'text',
            key: 'courseDetail.hero.ratingLabel',
            defaultValue: 'Note',
          },
          {
            id: 'studentsLabel',
            label: 'Label Étudiants',
            type: 'text',
            key: 'courseDetail.hero.studentsLabel',
            defaultValue: 'Étudiants',
          },
          {
            id: 'durationLabel',
            label: 'Label Durée',
            type: 'text',
            key: 'courseDetail.hero.durationLabel',
            defaultValue: 'Durée',
          },
          {
            id: 'lessonsLabel',
            label: 'Label Leçons',
            type: 'text',
            key: 'courseDetail.hero.lessonsLabel',
            defaultValue: 'Leçons',
          },
          {
            id: 'languageLabel',
            label: 'Label Langue',
            type: 'text',
            key: 'courseDetail.hero.languageLabel',
            defaultValue: 'Langue',
          },
          {
            id: 'instructorLabel',
            label: 'Label Instructeur',
            type: 'text',
            key: 'courseDetail.hero.instructorLabel',
            defaultValue: 'Créé par',
          },
        ],
      },
      {
        id: 'enrollment',
        name: 'Inscription',
        type: 'content',
        elements: [
          {
            id: 'enrollButton',
            label: "Bouton S'inscrire",
            type: 'text',
            key: 'courseDetail.enrollment.enrollButton',
            defaultValue: "S'inscrire maintenant",
          },
          {
            id: 'accessButton',
            label: 'Bouton Accéder',
            type: 'text',
            key: 'courseDetail.enrollment.accessButton',
            defaultValue: 'Accéder au cours',
          },
          {
            id: 'priceLabel',
            label: 'Label Prix',
            type: 'text',
            key: 'courseDetail.enrollment.priceLabel',
            defaultValue: 'Prix',
          },
          {
            id: 'includesTitle',
            label: 'Titre Inclus',
            type: 'text',
            key: 'courseDetail.enrollment.includesTitle',
            defaultValue: 'Ce cours comprend',
          },
          {
            id: 'lessonsCountLabel',
            label: 'Label Nombre de leçons',
            type: 'text',
            key: 'courseDetail.enrollment.lessonsCountLabel',
            defaultValue: 'leçons',
          },
          {
            id: 'durationTotalLabel',
            label: 'Label Durée totale',
            type: 'text',
            key: 'courseDetail.enrollment.durationTotalLabel',
            defaultValue: 'de contenu',
          },
          {
            id: 'certificateLabel',
            label: 'Label Certificat',
            type: 'text',
            key: 'courseDetail.enrollment.certificateLabel',
            defaultValue: 'Certificat de complétion',
          },
          {
            id: 'lifetimeAccessLabel',
            label: 'Label Accès à vie',
            type: 'text',
            key: 'courseDetail.enrollment.lifetimeAccessLabel',
            defaultValue: 'Accès à vie',
          },
        ],
      },
      {
        id: 'curriculum',
        name: 'Curriculum',
        type: 'content',
        elements: [
          {
            id: 'curriculumTitle',
            label: 'Titre Curriculum',
            type: 'text',
            key: 'courseDetail.curriculum.title',
            defaultValue: 'Curriculum du cours',
          },
          {
            id: 'sectionLabel',
            label: 'Label Section',
            type: 'text',
            key: 'courseDetail.curriculum.sectionLabel',
            defaultValue: 'Section',
          },
          {
            id: 'lessonLabel',
            label: 'Label Leçon',
            type: 'text',
            key: 'courseDetail.curriculum.lessonLabel',
            defaultValue: 'Leçon',
          },
          {
            id: 'previewLabel',
            label: 'Label Aperçu',
            type: 'text',
            key: 'courseDetail.curriculum.previewLabel',
            defaultValue: 'Aperçu',
          },
        ],
      },
      {
        id: 'objectives',
        name: 'Objectifs',
        type: 'content',
        elements: [
          {
            id: 'objectivesTitle',
            label: 'Titre Objectifs',
            type: 'text',
            key: 'courseDetail.objectives.title',
            defaultValue: 'Ce que vous allez apprendre',
          },
          {
            id: 'prerequisitesTitle',
            label: 'Titre Prérequis',
            type: 'text',
            key: 'courseDetail.objectives.prerequisitesTitle',
            defaultValue: 'Prérequis',
          },
        ],
      },
    ],
  },
  {
    id: 'bundleDetail',
    name: 'Détail Bundle',
    route: '/bundles/:bundleId',
    description: "Personnalisez tous les éléments de la page de détail d'un bundle",
    icon: Layers,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'backButton',
            label: 'Bouton Retour',
            type: 'text',
            key: 'bundleDetail.header.backButton',
            defaultValue: 'Retour',
          },
          {
            id: 'shareButton',
            label: 'Bouton Partager',
            type: 'text',
            key: 'bundleDetail.header.shareButton',
            defaultValue: 'Partager',
          },
        ],
      },
      {
        id: 'purchase',
        name: 'Achat',
        type: 'content',
        elements: [
          {
            id: 'buyButton',
            label: 'Bouton Acheter',
            type: 'text',
            key: 'bundleDetail.purchase.buyButton',
            defaultValue: 'Acheter le bundle',
          },
          {
            id: 'priceLabel',
            label: 'Label Prix',
            type: 'text',
            key: 'bundleDetail.purchase.priceLabel',
            defaultValue: 'Prix',
          },
          {
            id: 'savingsLabel',
            label: 'Label Économies',
            type: 'text',
            key: 'bundleDetail.purchase.savingsLabel',
            defaultValue: 'Vous économisez',
          },
          {
            id: 'valueLabel',
            label: 'Label Valeur',
            type: 'text',
            key: 'bundleDetail.purchase.valueLabel',
            defaultValue: 'Valeur totale',
          },
        ],
      },
      {
        id: 'products',
        name: 'Produits',
        type: 'content',
        elements: [
          {
            id: 'productsTitle',
            label: 'Titre Produits inclus',
            type: 'text',
            key: 'bundleDetail.products.title',
            defaultValue: 'Produits inclus dans ce bundle',
          },
          {
            id: 'productCountLabel',
            label: 'Label Nombre de produits',
            type: 'text',
            key: 'bundleDetail.products.countLabel',
            defaultValue: 'produits',
          },
          {
            id: 'viewProductButton',
            label: 'Bouton Voir produit',
            type: 'text',
            key: 'bundleDetail.products.viewProductButton',
            defaultValue: 'Voir le produit',
          },
        ],
      },
      {
        id: 'tabs',
        name: 'Onglets',
        type: 'content',
        elements: [
          {
            id: 'descriptionTab',
            label: 'Onglet Description',
            type: 'text',
            key: 'bundleDetail.tabs.description',
            defaultValue: 'Description',
          },
          {
            id: 'productsTab',
            label: 'Onglet Produits',
            type: 'text',
            key: 'bundleDetail.tabs.products',
            defaultValue: 'Produits',
          },
          {
            id: 'reviewsTab',
            label: 'Onglet Avis',
            type: 'text',
            key: 'bundleDetail.tabs.reviews',
            defaultValue: 'Avis',
          },
        ],
      },
    ],
  },
];

