import {
  Layout, Package, ShoppingCart, Users,
} from 'lucide-react';
import type { PageConfig } from './types';

export const publicPagesConfig: PageConfig[] = [
  {
    id: 'landing',
    name: "Page d'accueil",
    route: '/',
    description: "Personnalisez tous les éléments de la page d'accueil",
    icon: Layout,
    sections: [
      {
        id: 'hero',
        name: 'Section Hero',
        type: 'hero',
        elements: [
          {
            id: 'badge',
            label: 'Badge',
            type: 'text',
            key: 'landing.hero.badge',
            defaultValue: "La plateforme e-commerce tout-en-un pour l'Afrique",
          },
          {
            id: 'title',
            label: 'Titre principal',
            type: 'textarea',
            key: 'landing.hero.title',
            defaultValue: 'Créez votre boutique en ligne en quelques minutes',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'landing.hero.subtitle',
            defaultValue:
              'Vendez vos produits digitaux et physiques avec une plateforme complète, sécurisée et facile à utiliser.',
          },
          {
            id: 'ctaPrimary',
            label: 'Bouton principal',
            type: 'text',
            key: 'landing.hero.ctaPrimary',
            defaultValue: 'Créer ma boutique gratuitement',
          },
          {
            id: 'ctaSecondary',
            label: 'Bouton secondaire',
            type: 'text',
            key: 'landing.hero.ctaSecondary',
            defaultValue: 'Voir la démo',
          },
          {
            id: 'bgColor',
            label: 'Couleur de fond',
            type: 'color',
            key: 'landing.hero.bgColor',
            defaultValue: '#1e293b',
          },
          {
            id: 'textColor',
            label: 'Couleur du texte',
            type: 'color',
            key: 'landing.hero.textColor',
            defaultValue: '#ffffff',
          },
          { id: 'bgImage', label: 'Image de fond', type: 'image', key: 'landing.hero.bgImage' },
        ],
      },
      {
        id: 'stats',
        name: 'Statistiques',
        type: 'content',
        elements: [
          {
            id: 'usersLabel',
            label: 'Label utilisateurs',
            type: 'text',
            key: 'landing.stats.users',
            defaultValue: 'Utilisateurs',
          },
          {
            id: 'salesLabel',
            label: 'Label ventes',
            type: 'text',
            key: 'landing.stats.sales',
            defaultValue: 'Ventes',
          },
          {
            id: 'storesLabel',
            label: 'Label boutiques',
            type: 'text',
            key: 'landing.stats.stores',
            defaultValue: 'Boutiques',
          },
        ],
      },
      {
        id: 'features',
        name: 'Section Fonctionnalités',
        type: 'features',
        elements: [
          {
            id: 'title',
            label: 'Titre',
            type: 'text',
            key: 'landing.features.title',
            defaultValue: 'Fonctionnalités clés',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'landing.features.subtitle',
            defaultValue: 'Tout ce dont vous avez besoin pour réussir en ligne',
          },
        ],
      },
      {
        id: 'testimonials',
        name: 'Témoignages',
        type: 'testimonials',
        elements: [
          {
            id: 'title',
            label: 'Titre',
            type: 'text',
            key: 'landing.testimonials.title',
            defaultValue: 'Ils réussissent avec Emarzona',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'landing.testimonials.subtitle',
            defaultValue: "Rejoignez des centaines d'entrepreneurs qui développent leur activité",
          },
        ],
      },
    ],
  },
  {
    id: 'marketplace',
    name: 'Marketplace',
    route: '/marketplace',
    description: 'Personnalisez tous les éléments de la page marketplace',
    icon: ShoppingCart,
    sections: [
      {
        id: 'hero',
        name: 'Section Hero',
        type: 'hero',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'textarea',
            key: 'marketplace.hero.title',
            defaultValue: 'Découvrez notre marketplace',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'marketplace.hero.subtitle',
            defaultValue: 'Explorez des milliers de produits digitaux',
          },
          {
            id: 'tagline',
            label: 'Tagline',
            type: 'text',
            key: 'marketplace.hero.tagline',
            defaultValue: 'Tout ce dont vous avez besoin',
          },
          {
            id: 'searchPlaceholder',
            label: 'Placeholder recherche',
            type: 'text',
            key: 'marketplace.searchPlaceholder',
            defaultValue: 'Rechercher un produit...',
          },
          {
            id: 'bgGradient',
            label: 'Dégradé de fond',
            type: 'color',
            key: 'marketplace.hero.bgGradient',
            defaultValue: '#1e293b',
          },
        ],
      },
      {
        id: 'cta',
        name: 'Call to Action',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre CTA',
            type: 'text',
            key: 'marketplace.cta.title',
            defaultValue: 'Prêt à commencer ?',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre CTA',
            type: 'textarea',
            key: 'marketplace.cta.subtitle',
            defaultValue: "Rejoignez des milliers d'entrepreneurs",
          },
          {
            id: 'startFree',
            label: 'Bouton Commencer gratuitement',
            type: 'text',
            key: 'marketplace.cta.startFree',
            defaultValue: 'Commencer gratuitement',
          },
          {
            id: 'joinCommunity',
            label: 'Bouton Rejoindre communauté',
            type: 'text',
            key: 'marketplace.cta.joinCommunity',
            defaultValue: 'Rejoindre la communauté',
          },
        ],
      },
      {
        id: 'filters',
        name: 'Filtres',
        type: 'content',
        elements: [
          {
            id: 'filtersActive',
            label: 'Label Filtres actifs',
            type: 'text',
            key: 'marketplace.filtersActive',
            defaultValue: 'Filtres actifs',
          },
          {
            id: 'filterCategory',
            label: 'Label Catégorie',
            type: 'text',
            key: 'marketplace.filterLabels.category',
            defaultValue: 'Catégorie',
          },
          {
            id: 'filterType',
            label: 'Label Type',
            type: 'text',
            key: 'marketplace.filterLabels.type',
            defaultValue: 'Type',
          },
          {
            id: 'filterPriceRange',
            label: 'Label Fourchette prix',
            type: 'text',
            key: 'marketplace.filterLabels.priceRange',
            defaultValue: 'Fourchette de prix',
          },
          {
            id: 'filterVerified',
            label: 'Label Vérifié',
            type: 'text',
            key: 'marketplace.filterLabels.verified',
            defaultValue: 'Vérifié',
          },
          {
            id: 'filterFeatured',
            label: 'Label En vedette',
            type: 'text',
            key: 'marketplace.filterLabels.featured',
            defaultValue: 'En vedette',
          },
          {
            id: 'filterTag',
            label: 'Label Tag',
            type: 'text',
            key: 'marketplace.filterLabels.tag',
            defaultValue: 'Tag',
          },
          {
            id: 'filterClear',
            label: 'Bouton Effacer',
            type: 'text',
            key: 'marketplace.filterLabels.clear',
            defaultValue: 'Effacer',
          },
          {
            id: 'filterAll',
            label: 'Label Tout',
            type: 'text',
            key: 'marketplace.filterLabels.all',
            defaultValue: 'Tout',
          },
        ],
      },
    ],
  },
  {
    id: 'storefront',
    name: 'Storefront',
    route: ':slug.myemarzona.shop',
    description: 'Personnalisez tous les éléments de la page boutique',
    icon: ShoppingCart,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre',
            type: 'text',
            key: 'storefront.header.title',
            defaultValue: 'Boutique',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'storefront.header.subtitle',
            defaultValue: 'Découvrez nos produits',
          },
          {
            id: 'noProducts',
            label: 'Message Aucun produit',
            type: 'textarea',
            key: 'storefront.noProducts',
            defaultValue: 'Aucun produit disponible pour le moment',
          },
          {
            id: 'loading',
            label: 'Message Chargement',
            type: 'text',
            key: 'storefront.loading',
            defaultValue: 'Chargement des produits...',
          },
        ],
      },
    ],
  },
  {
    id: 'productDetail',
    name: 'Détail Produit',
    route: ':slug.myemarzona.shop/products/:productSlug',
    description: 'Personnalisez tous les éléments de la page produit',
    icon: Package,
    sections: [
      {
        id: 'cta',
        name: 'Call to Action',
        type: 'content',
        elements: [
          {
            id: 'addToCart',
            label: 'Texte "Ajouter au panier"',
            type: 'text',
            key: 'productDetail.cta.addToCart',
            defaultValue: 'Ajouter au panier',
          },
          {
            id: 'buyNow',
            label: 'Texte "Acheter maintenant"',
            type: 'text',
            key: 'productDetail.cta.buyNow',
            defaultValue: 'Acheter maintenant',
          },
          {
            id: 'outOfStock',
            label: 'Message Rupture de stock',
            type: 'text',
            key: 'productDetail.outOfStock',
            defaultValue: 'Rupture de stock',
          },
          {
            id: 'freeProduct',
            label: 'Label Produit gratuit',
            type: 'text',
            key: 'productDetail.freeProduct',
            defaultValue: 'Gratuit',
          },
          {
            id: 'loading',
            label: 'Message Chargement',
            type: 'text',
            key: 'productDetail.loading',
            defaultValue: 'Chargement du produit...',
          },
        ],
      },
    ],
  },
  {
    id: 'cart',
    name: 'Panier',
    route: '/cart',
    description: 'Personnalisez tous les éléments de la page panier',
    icon: ShoppingCart,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre',
            type: 'text',
            key: 'cart.title',
            defaultValue: 'Mon panier',
          },
          {
            id: 'emptyMessage',
            label: 'Message panier vide',
            type: 'textarea',
            key: 'cart.emptyMessage',
            defaultValue: 'Votre panier est vide',
          },
          {
            id: 'emptySubtitle',
            label: 'Sous-titre panier vide',
            type: 'textarea',
            key: 'cart.emptySubtitle',
            defaultValue: 'Ajoutez des produits pour commencer',
          },
          {
            id: 'emptyCta',
            label: 'Bouton Continuer shopping',
            type: 'text',
            key: 'cart.emptyCta',
            defaultValue: 'Continuer mes achats',
          },
          {
            id: 'clearCart',
            label: 'Bouton Vider panier',
            type: 'text',
            key: 'cart.clearCart',
            defaultValue: 'Vider le panier',
          },
          {
            id: 'itemCount',
            label: "Label Nombre d'articles",
            type: 'text',
            key: 'cart.itemCount',
            defaultValue: 'articles',
          },
        ],
      },
    ],
  },
  {
    id: 'auth',
    name: 'Authentification',
    route: '/auth',
    description: 'Personnalisez tous les éléments de la page connexion/inscription',
    icon: Users,
    sections: [
      {
        id: 'header',
        name: 'En-tête',
        type: 'content',
        elements: [
          {
            id: 'loginTitle',
            label: 'Titre connexion',
            type: 'text',
            key: 'auth.login.title',
            defaultValue: 'Connexion',
          },
          {
            id: 'signupTitle',
            label: 'Titre inscription',
            type: 'text',
            key: 'auth.signup.title',
            defaultValue: 'Créer un compte',
          },
          {
            id: 'welcomeMessage',
            label: 'Message de bienvenue',
            type: 'textarea',
            key: 'auth.welcome',
            defaultValue: 'Bienvenue sur Emarzona',
          },
          {
            id: 'loginButton',
            label: 'Bouton Se connecter',
            type: 'text',
            key: 'auth.login.button',
            defaultValue: 'Se connecter',
          },
          {
            id: 'signupButton',
            label: "Bouton S'inscrire",
            type: 'text',
            key: 'auth.signup.button',
            defaultValue: "S'inscrire",
          },
          {
            id: 'forgotPassword',
            label: 'Lien Mot de passe oublié',
            type: 'text',
            key: 'auth.forgotPassword.link',
            defaultValue: 'Mot de passe oublié ?',
          },
          {
            id: 'alreadyHaveAccount',
            label: 'Message Déjà un compte',
            type: 'text',
            key: 'auth.alreadyHaveAccount',
            defaultValue: 'Déjà un compte ?',
          },
          {
            id: 'noAccount',
            label: 'Message Pas de compte',
            type: 'text',
            key: 'auth.noAccount',
            defaultValue: 'Pas encore de compte ?',
          },
        ],
      },
    ],
  },
  {
    id: 'community',
    name: 'Communauté',
    route: '/community',
    description: 'Personnalisez tous les éléments de la page communauté',
    icon: Users,
    sections: [
      {
        id: 'hero',
        name: 'Section Hero',
        type: 'hero',
        elements: [
          {
            id: 'title',
            label: 'Titre principal',
            type: 'textarea',
            key: 'community.hero.title',
            defaultValue: 'Rejoignez notre communauté',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre',
            type: 'textarea',
            key: 'community.hero.subtitle',
            defaultValue: "Échangez avec d'autres entrepreneurs et développez votre activité",
          },
          {
            id: 'ctaButton',
            label: 'Bouton CTA',
            type: 'text',
            key: 'community.hero.ctaButton',
            defaultValue: 'Rejoindre maintenant',
          },
          {
            id: 'bgColor',
            label: 'Couleur de fond',
            type: 'color',
            key: 'community.hero.bgColor',
            defaultValue: '#1e293b',
          },
          {
            id: 'textColor',
            label: 'Couleur du texte',
            type: 'color',
            key: 'community.hero.textColor',
            defaultValue: '#ffffff',
          },
        ],
      },
      {
        id: 'features',
        name: 'Fonctionnalités',
        type: 'content',
        elements: [
          {
            id: 'title',
            label: 'Titre section',
            type: 'text',
            key: 'community.features.title',
            defaultValue: 'Pourquoi rejoindre ?',
          },
          {
            id: 'subtitle',
            label: 'Sous-titre section',
            type: 'textarea',
            key: 'community.features.subtitle',
            defaultValue: 'Découvrez tous les avantages de notre communauté',
          },
        ],
      },
      {
        id: 'stats',
        name: 'Statistiques',
        type: 'content',
        elements: [
          {
            id: 'membersLabel',
            label: 'Label Membres',
            type: 'text',
            key: 'community.stats.members',
            defaultValue: 'Membres',
          },
          {
            id: 'postsLabel',
            label: 'Label Publications',
            type: 'text',
            key: 'community.stats.posts',
            defaultValue: 'Publications',
          },
          {
            id: 'topicsLabel',
            label: 'Label Sujets',
            type: 'text',
            key: 'community.stats.topics',
            defaultValue: 'Sujets',
          },
        ],
      },
    ],
  },
];
