import { Settings } from 'lucide-react';
import type { ContextSidebarConfig } from '@/config/navigation.context.types';

/** Remaining context sidebars migrated in Phase 6 */
export const PHASE6_CONTEXT_CONFIGS = {
  sales: {
    id: 'sales',
    sectionKey: 'ventes_logistique',
    additionalSectionKeys: ['finance_paiements'],
    rootPath: '/dashboard/orders',
    breadcrumbSectionKey: 'ventes_logistique',
    ariaLabel: 'Navigation ventes',
    enablePlanLock: true,
    collapsibleGroups: true,
    includePaths: [
      '/dashboard/orders',
      '/dashboard/store/team',
      '/dashboard/tasks',
      '/dashboard/withdrawals',
      '/dashboard/taxes',
      '/dashboard/payments',
      '/dashboard/payments-customers',
      '/dashboard/pay-balance',
      '/dashboard/payment-management',
      '/dashboard/payment-methods',
      '/dashboard/payment-connections',
      '/dashboard/advanced-orders',
      '/vendor/messaging',
      '/dashboard/bookings',
      '/dashboard/services/calendar',
      '/dashboard/services/recurring-bookings',
      '/dashboard/advanced-calendar',
      '/dashboard/service-management',
      '/dashboard/recurring-bookings',
      '/dashboard/services/staff-availability',
      '/dashboard/services/resource-conflicts',
      '/dashboard/services/calendar-integrations',
      '/dashboard/services/waitlist',
      '/dashboard/services/reminders',
      '/dashboard/inventory',
      '/dashboard/shipping',
      '/dashboard/shipping-services',
      '/dashboard/contact-shipping-service',
      '/dashboard/batch-shipping',
      '/dashboard/product-kits',
      '/dashboard/demand-forecasting',
      '/dashboard/inventory-analytics',
      '/dashboard/cost-optimization',
      '/dashboard/suppliers',
      '/dashboard/warehouses',
      '/dashboard/physical-inventory',
      '/dashboard/physical-analytics',
      '/dashboard/physical-lots',
      '/dashboard/physical-serial-tracking',
      '/dashboard/physical-barcode-scanner',
      '/dashboard/physical-preorders',
      '/dashboard/physical-backorders',
      '/dashboard/physical-bundles',
      '/dashboard/physical-promotions',
      '/dashboard/multi-currency',
    ],
    groups: [
      {
        groupKey: 'commandes_clients',
        defaultLabel: 'Commandes & Clients',
        paths: [
          '/dashboard/orders',
          '/dashboard/store/team',
          '/dashboard/tasks',
          '/dashboard/advanced-orders',
          '/vendor/messaging',
        ],
      },
      {
        groupKey: 'finance_paiements',
        defaultLabel: 'Finance & Paiements',
        paths: [
          '/dashboard/payments',
          '/dashboard/taxes',
          '/dashboard/payments-customers',
          '/dashboard/pay-balance',
          '/dashboard/payment-management',
          '/dashboard/payment-methods',
          '/dashboard/payment-connections',
          '/dashboard/withdrawals',
        ],
      },
      {
        groupKey: 'services_reservations',
        defaultLabel: 'Services & Réservations',
        paths: [
          '/dashboard/bookings',
          '/dashboard/services/calendar',
          '/dashboard/services/recurring-bookings',
          '/dashboard/advanced-calendar',
          '/dashboard/service-management',
          '/dashboard/recurring-bookings',
          '/dashboard/services/staff-availability',
          '/dashboard/services/resource-conflicts',
          '/dashboard/services/calendar-integrations',
          '/dashboard/services/waitlist',
          '/dashboard/services/reminders',
        ],
      },
      {
        groupKey: 'logistique_inventaire',
        defaultLabel: 'Logistique & Inventaire',
        paths: [
          '/dashboard/inventory',
          '/dashboard/shipping',
          '/dashboard/shipping-services',
          '/dashboard/contact-shipping-service',
          '/dashboard/batch-shipping',
          '/dashboard/product-kits',
          '/dashboard/inventory-analytics',
        ],
      },
      {
        groupKey: 'optimisation',
        defaultLabel: 'Optimisation',
        paths: [
          '/dashboard/demand-forecasting',
          '/dashboard/cost-optimization',
          '/dashboard/suppliers',
          '/dashboard/warehouses',
        ],
      },
      {
        groupKey: 'produits_physiques',
        defaultLabel: 'Produits Physiques',
        paths: [
          '/dashboard/physical-products',
          '/dashboard/physical-inventory',
          '/dashboard/physical-analytics',
          '/dashboard/physical-lots',
          '/dashboard/physical-serial-tracking',
          '/dashboard/physical-barcode-scanner',
          '/dashboard/physical-preorders',
          '/dashboard/physical-backorders',
          '/dashboard/physical-bundles',
          '/dashboard/physical-promotions',
          '/dashboard/multi-currency',
        ],
      },
    ],
  },
  bookings: {
    id: 'bookings',
    sectionKey: 'ventes_logistique',
    rootPath: '/dashboard/bookings',
    breadcrumbSectionKey: 'reservations',
    ariaLabel: 'Navigation réservations',
    collapsibleGroups: true,
    includePaths: [
      '/dashboard/bookings',
      '/dashboard/advanced-calendar',
      '/dashboard/service-management',
      '/dashboard/recurring-bookings',
      '/dashboard/services/staff-availability',
      '/dashboard/services/resource-conflicts',
      '/dashboard/services/calendar',
      '/dashboard/services/recurring-bookings',
      '/dashboard/services/calendar-integrations',
      '/dashboard/services/waitlist',
      '/dashboard/services/reminders',
    ],
    groups: [
      {
        groupKey: 'reservations',
        defaultLabel: 'Réservations',
        paths: [
          '/dashboard/bookings',
          '/dashboard/recurring-bookings',
          '/dashboard/service-management',
        ],
      },
      {
        groupKey: 'calendriers',
        defaultLabel: 'Calendriers',
        paths: [
          '/dashboard/advanced-calendar',
          '/dashboard/services/calendar',
          '/dashboard/services/recurring-bookings',
          '/dashboard/services/staff-availability',
        ],
      },
      {
        groupKey: 'automatisation',
        defaultLabel: 'Automatisation',
        paths: [
          '/dashboard/services/calendar-integrations',
          '/dashboard/services/waitlist',
          '/dashboard/services/reminders',
          '/dashboard/services/resource-conflicts',
        ],
      },
    ],
  },
  inventory: {
    id: 'inventory',
    sectionKey: 'ventes_logistique',
    rootPath: '/dashboard/inventory',
    breadcrumbSectionKey: 'inventaire',
    ariaLabel: 'Navigation inventaire',
    enablePlanLock: true,
    collapsibleGroups: true,
    includePaths: [
      '/dashboard/inventory',
      '/dashboard/product-kits',
      '/dashboard/demand-forecasting',
      '/dashboard/cost-optimization',
      '/dashboard/suppliers',
      '/dashboard/warehouses',
      '/dashboard/physical-inventory',
      '/dashboard/physical-lots',
      '/dashboard/physical-serial-tracking',
      '/dashboard/physical-barcode-scanner',
      '/dashboard/physical-preorders',
      '/dashboard/physical-backorders',
      '/dashboard/inventory-analytics',
    ],
    groups: [
      {
        groupKey: 'stocks',
        defaultLabel: 'Stocks',
        paths: [
          '/dashboard/inventory',
          '/dashboard/physical-inventory',
          '/dashboard/physical-lots',
          '/dashboard/inventory-analytics',
        ],
      },
      {
        groupKey: 'suivi_qualite',
        defaultLabel: 'Suivi & traçabilité',
        paths: [
          '/dashboard/physical-serial-tracking',
          '/dashboard/physical-barcode-scanner',
          '/dashboard/physical-preorders',
          '/dashboard/physical-backorders',
        ],
      },
      {
        groupKey: 'optimisation_stock',
        defaultLabel: 'Optimisation',
        paths: [
          '/dashboard/product-kits',
          '/dashboard/demand-forecasting',
          '/dashboard/cost-optimization',
          '/dashboard/suppliers',
          '/dashboard/warehouses',
        ],
      },
    ],
  },
  shipping: {
    id: 'shipping',
    sectionKey: 'ventes_logistique',
    rootPath: '/dashboard/shipping',
    breadcrumbSectionKey: 'expeditions',
    ariaLabel: 'Navigation expéditions',
    enablePlanLock: true,
    includePaths: [
      '/dashboard/shipping',
      '/dashboard/shipping-services',
      '/dashboard/contact-shipping-service',
      '/dashboard/batch-shipping',
    ],
  },
  store: {
    id: 'store',
    sectionKey: 'principal',
    additionalSectionKeys: ['ventes_logistique'],
    rootPath: '/dashboard/store',
    breadcrumbSectionKey: 'boutique',
    ariaLabel: 'Navigation boutique',
    includePaths: ['/dashboard/store', '/dashboard/store/team'],
    supplementStaticItems: [
      {
        title: 'Paramètres Boutique',
        url: '/dashboard/settings?tab=store',
        icon: Settings,
      },
    ],
  },
  promotions: {
    id: 'promotions',
    sectionKey: 'marketing_croissance',
    rootPath: '/dashboard/promotions',
    breadcrumbSectionKey: 'promotions',
    ariaLabel: 'Navigation promotions',
    includePaths: [
      '/dashboard/promotions',
      '/dashboard/coupons',
      '/dashboard/promotions/stats',
      '/dashboard/abandoned-carts',
    ],
  },
  courses: {
    id: 'courses',
    sectionKey: 'produits_cours',
    additionalSectionKeys: ['mon_compte'],
    rootPath: '/account/courses',
    breadcrumbSectionKey: 'cours',
    ariaLabel: 'Navigation cours',
    collapsibleGroups: true,
    includePaths: [
      '/account/courses',
      '/dashboard/courses/new',
      '/dashboard/courses',
      '/dashboard/courses/live-sessions',
      '/dashboard/courses/assignments',
      '/dashboard/cohorts',
      '/dashboard/reviews',
    ],
    groups: [
      {
        groupKey: 'mes_cours',
        defaultLabel: 'Mes cours',
        paths: ['/account/courses'],
      },
      {
        groupKey: 'gestion_cours',
        defaultLabel: 'Gestion (vendeur)',
        paths: [
          '/dashboard/courses/new',
          '/dashboard/courses',
          '/dashboard/courses/live-sessions',
          '/dashboard/courses/assignments',
          '/dashboard/cohorts',
          '/dashboard/reviews',
        ],
      },
    ],
  },
  affiliate: {
    id: 'affiliate',
    sectionKey: 'marketing_croissance',
    rootPath: '/affiliate/dashboard',
    breadcrumbSectionKey: 'affiliation',
    ariaLabel: 'Navigation affiliation',
    collapsibleGroups: true,
    includePaths: [
      '/affiliate/dashboard',
      '/affiliate/courses',
      '/dashboard/affiliates',
      '/dashboard/referrals',
      '/dashboard/store-affiliates',
    ],
    groups: [
      {
        groupKey: 'tableau_bord',
        defaultLabel: 'Tableau de bord',
        paths: ['/affiliate/dashboard', '/affiliate/courses'],
      },
      {
        groupKey: 'programmes',
        defaultLabel: 'Programmes',
        paths: ['/dashboard/affiliates', '/dashboard/referrals', '/dashboard/store-affiliates'],
      },
    ],
  },
  account: {
    id: 'account',
    sectionKey: 'mon_compte',
    rootPath: '/account',
    breadcrumbSectionKey: 'mon_compte',
    ariaLabel: 'Navigation compte',
    persona: 'buyer',
    collapsibleGroups: true,
    includePaths: [
      '/account',
      '/account/profile',
      '/account/orders',
      '/account/downloads',
      '/account/digital',
      '/account/physical',
      '/account/courses',
      '/account/wishlist',
      '/account/alerts',
      '/account/invoices',
      '/account/returns',
      '/account/gift-cards',
      '/account/warranties',
      '/account/bookings',
      '/account/artist',
      '/account/loyalty',
      '/checkout/multi-store-tracking',
    ],
    groups: [
      {
        groupKey: 'profil_compte',
        defaultLabel: 'Mon compte',
        paths: ['/account', '/account/profile', '/account/wishlist', '/account/alerts'],
      },
      {
        groupKey: 'achats',
        defaultLabel: 'Achats & facturation',
        paths: [
          '/account/orders',
          '/account/invoices',
          '/account/returns',
          '/account/gift-cards',
          '/account/warranties',
        ],
      },
      {
        groupKey: 'portails',
        defaultLabel: 'Mes portails',
        paths: ['/account/downloads', '/account/digital', '/account/physical', '/account/courses'],
      },
      {
        groupKey: 'services_fidelite',
        defaultLabel: 'Services & fidélité',
        paths: [
          '/account/bookings',
          '/account/artist',
          '/account/loyalty',
          '/checkout/multi-store-tracking',
        ],
      },
    ],
  },
  digitalPortal: {
    id: 'digitalPortal',
    sectionKey: 'mon_compte',
    additionalSectionKeys: ['produits_cours'],
    rootPath: '/account/digital',
    breadcrumbSectionKey: 'portail_digital',
    ariaLabel: 'Navigation portail digital',
    persona: 'buyer',
    collapsibleGroups: true,
    includePaths: [
      '/account/digital',
      '/account/downloads',
      '/dashboard/my-licenses',
      '/dashboard/digital-products',
      '/dashboard/digital-products/bundles',
      '/dashboard/digital-products/bundles/create',
      '/dashboard/digital/updates',
      '/dashboard/my-downloads',
      '/dashboard/license-management',
    ],
    groups: [
      {
        groupKey: 'mon_portail_digital',
        defaultLabel: 'Mon portail',
        paths: ['/account/digital', '/account/downloads', '/dashboard/my-licenses'],
      },
      {
        groupKey: 'gestion_digitale',
        defaultLabel: 'Gestion (vendeur)',
        paths: [
          '/dashboard/digital-products',
          '/dashboard/digital-products/bundles',
          '/dashboard/digital-products/bundles/create',
          '/dashboard/digital/updates',
          '/dashboard/my-downloads',
          '/dashboard/license-management',
        ],
      },
    ],
  },
  physicalPortal: {
    id: 'physicalPortal',
    sectionKey: 'mon_compte',
    additionalSectionKeys: ['ventes_logistique'],
    rootPath: '/account/physical',
    breadcrumbSectionKey: 'portail_physique',
    ariaLabel: 'Navigation portail physique',
    persona: 'buyer',
    collapsibleGroups: true,
    includePaths: [
      '/account/physical',
      '/account/orders',
      '/account/returns',
      '/dashboard/physical-inventory',
      '/dashboard/physical-analytics',
      '/dashboard/physical-lots',
      '/dashboard/physical-serial-tracking',
      '/dashboard/physical-barcode-scanner',
      '/dashboard/physical-preorders',
      '/dashboard/physical-backorders',
      '/dashboard/physical-bundles',
      '/dashboard/physical-promotions',
      '/dashboard/multi-currency',
    ],
    groups: [
      {
        groupKey: 'mon_portail_physique',
        defaultLabel: 'Mon portail',
        paths: ['/account/physical', '/account/orders', '/account/returns'],
      },
      {
        groupKey: 'stocks_suivi',
        defaultLabel: 'Stocks & suivi',
        paths: [
          '/dashboard/physical-inventory',
          '/dashboard/physical-analytics',
          '/dashboard/physical-lots',
          '/dashboard/physical-serial-tracking',
          '/dashboard/physical-barcode-scanner',
        ],
      },
      {
        groupKey: 'operations_physiques',
        defaultLabel: 'Opérations',
        paths: [
          '/dashboard/physical-preorders',
          '/dashboard/physical-backorders',
          '/dashboard/physical-bundles',
          '/dashboard/physical-promotions',
          '/dashboard/multi-currency',
        ],
      },
    ],
  },
} as const satisfies Record<string, ContextSidebarConfig>;

export type Phase6ContextConfigId = keyof typeof PHASE6_CONTEXT_CONFIGS;
