-- Afficher la clé de licence dans l'email de confirmation digitale.

UPDATE public.email_templates
SET
  html_content = jsonb_build_object(
    'fr', $fr$<h1>Merci {{user_name}} !</h1><p>Votre commande #{{order_number}} sur <strong>{{store_name}}</strong> a bien été confirmée.</p><p>Produit : {{product_name}}</p><p>Prix : {{price}}</p>{{#if license_key}}<div style="margin:20px 0;padding:16px;background:#f4f4f5;border-radius:8px;border:1px solid #e4e4e7;"><p style="margin:0 0 6px;font-size:13px;color:#52525b;">Votre clé de licence</p><p style="margin:0;font-size:18px;font-weight:700;letter-spacing:0.06em;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;">{{license_key}}</p></div>{{/if}}{{#if download_links_html}}<p>Vos fichiers :</p>{{download_links_html}}{{/if}}<p style="margin-top:20px;"><a href="{{download_link}}" style="display:inline-block;padding:12px 24px;background:#000;color:#fff;text-decoration:none;border-radius:6px;font-weight:bold;">Accéder à mes achats digitaux</a></p>{{#if whatsapp_link}}<p style="margin-top:20px;">Besoin d'aide ? <a href="{{whatsapp_link}}">Contacter le vendeur sur WhatsApp</a></p>{{/if}}$fr$,
    'en', $en$<h1>Thank you {{user_name}}!</h1><p>Your order #{{order_number}} on <strong>{{store_name}}</strong> is confirmed.</p><p>Product: {{product_name}}</p><p>Price: {{price}}</p>{{#if license_key}}<div style="margin:20px 0;padding:16px;background:#f4f4f5;border-radius:8px;border:1px solid #e4e4e7;"><p style="margin:0 0 6px;font-size:13px;color:#52525b;">Your license key</p><p style="margin:0;font-size:18px;font-weight:700;letter-spacing:0.06em;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;">{{license_key}}</p></div>{{/if}}{{#if download_links_html}}<p>Your files:</p>{{download_links_html}}{{/if}}<p style="margin-top:20px;"><a href="{{download_link}}" style="display:inline-block;padding:12px 24px;background:#000;color:#fff;text-decoration:none;border-radius:6px;font-weight:bold;">Access my digital downloads</a></p>{{#if whatsapp_link}}<p style="margin-top:20px;">Need help? <a href="{{whatsapp_link}}">Contact seller on WhatsApp</a></p>{{/if}}$en$
  ),
  variables = '["{{user_name}}", "{{order_number}}", "{{product_name}}", "{{download_link}}", "{{download_links_html}}", "{{store_name}}", "{{price}}", "{{whatsapp_link}}", "{{license_key}}"]'::jsonb,
  updated_at = NOW()
WHERE slug = 'order-confirmation-digital';
