// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
if (!SUPABASE_URL) {
  throw new Error(
    '❌ VITE_SUPABASE_URL is required. Add it to your .env file. ' +
    'See .env.example for details.'
  );
}

/**
 * Clé publique Supabase.
 * En environnement de test (Vitest CI), on utilise une valeur factice pour éviter l'erreur
 * \"supabaseKey is required\" tout en restant inoffensif côté données.
 */
const rawPublishableKey =
  import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

const SUPABASE_PUBLISHABLE_KEY =
  typeof rawPublishableKey === 'string' &&
  rawPublishableKey.trim().length > 0 &&
  rawPublishableKey !== 'sb_publishable_votre_cle' &&
  rawPublishableKey !== 'mock-key'
    ? rawPublishableKey
    : import.meta.env.MODE === 'test'
      ? 'test-supabase-key'
      : rawPublishableKey;

/** Diagnostic E2E (masqué) — clé réellement passée à createClient. */
export const supabaseClientRuntimeMeta = {
  url: SUPABASE_URL,
  keyLength: SUPABASE_PUBLISHABLE_KEY.length,
  keyPrefix:
    SUPABASE_PUBLISHABLE_KEY.length > 0 ? `${SUPABASE_PUBLISHABLE_KEY.slice(0, 16)}…` : '(empty)',
  keyKind: SUPABASE_PUBLISHABLE_KEY.startsWith('sb_publishable_')
    ? 'publishable'
    : SUPABASE_PUBLISHABLE_KEY === 'mock-key' || SUPABASE_PUBLISHABLE_KEY === 'test-supabase-key'
      ? 'mock'
      : SUPABASE_PUBLISHABLE_KEY.startsWith('eyJ')
        ? 'jwt'
        : SUPABASE_PUBLISHABLE_KEY.length === 0
          ? 'empty'
          : 'other',
} as const;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
