// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL || 'https://hbdnzajbyjakdhuavrvb.supabase.co';

/**
 * Clé publique Supabase.
 * En environnement de test (Vitest CI), on utilise une valeur factice pour éviter l'erreur
 * \"supabaseKey is required\" tout en restant inoffensif côté données.
 */
const rawPublishableKey =
  import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

const SUPABASE_PUBLISHABLE_KEY =
  (rawPublishableKey &&
    typeof rawPublishableKey === 'string' &&
    rawPublishableKey.trim().length > 0 &&
    rawPublishableKey !== 'sb_publishable_votre_cle' &&
    rawPublishableKey !== 'mock-key') ||
  import.meta.env.MODE !== 'test'
    ? rawPublishableKey
    : 'test-supabase-key';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
